// Package buildrt is the shared runtime for executing a boru program and
// printing its residual stack. It is the single implementation of "evaluate
// source, print the result" used by three callers:
//
//   - the `run` / `do` subcommands (via Eval),
//   - a standalone executable produced by `boru build` (self-embedding
//     launcher: cmd/go decodes an appended payload and calls Main),
//   - a `--native` binary generated by `boru build` (its tiny main.go calls
//     Main directly).
//
// Keeping the eval+print core here — depending only on the lang package and
// the standard library — lets the generated binary reuse it without importing
// the heavy `run` package (flag, repl, check).
package buildrt

import (
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	lang "github.com/boru-lang/boru/lang/go"
	"github.com/boru-lang/boru/lang/go/capabilities"
	"github.com/boru-lang/boru/lang/go/modules"
	"github.com/boru-lang/boru/lang/go/policy"

	"github.com/boru-lang/boru/cmd/go/internal/termback"

	"github.com/boru-lang/boru/cmd/go/internal/wire"
)

// CompileMode selects which execution engine Eval/Main drives: the
// best-effort bytecode compiler (silent fallback — the default), the
// interpreter (--no-compile), or the bytecode compiler in FORCE mode
// (error if uncompilable).
// It mirrors the run subcommand's mode; run type-aliases this type so there is
// a single source of truth that the generated binary can reference without
// importing run.
type CompileMode int

const (
	// CompileOff runs the interpreter (the `--no-compile` flag).
	CompileOff CompileMode = iota
	// CompileTry runs the bytecode compiler when the program is compilable and
	// silently falls back to the interpreter otherwise — the default.
	CompileTry
	// CompileForce REQUIRES the bytecode path: an uncompilable program (or a VM
	// soundness assertion) aborts with the refusal reason rather than falling
	// back (the `--force-compile` flag).
	CompileForce
)

// langNew is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive the init-error arms of Eval and Main — lang.New only fails on
// registry construction errors that no Options value can provoke.
var langNew = lang.New

// registerTerminalBackend wires the real-TTY tuikit backend onto the
// runtime's registry so `import "boru:tui"` words reach the terminal
// (design/TUI-IMPLEMENTATION-PLAN.0.md P3). Registration is cheap and
// pre-import-safe; failure means a backend is already registered on
// this registry, which is exactly the state we want.
func registerTerminalBackend(a *lang.Boru) {
	_ = modules.RegisterHostTui(a.NativeRegistry(), termback.Spec())
}

// Eval runs source under Options o with the engine selected by mode, then
// writes the residual stack (carriers joined by spaces) to w. This is the body
// the run subcommand's EvalOptionsMode forwards to.
func Eval(w io.Writer, source string, o lang.Options, mode CompileMode) error {
	return EvalColor(w, source, o, mode, false)
}

// EvalColor is Eval with the color decision resolved by the caller
// (lang.ResolveColor over the stream the error will be printed to):
// a structured BoruError renders through the diagnostic renderer with
// the ANSI palette; color=false keeps the byte-identical plain text.
func EvalColor(w io.Writer, source string, o lang.Options, mode CompileMode, color bool) error {
	return EvalReport(w, nil, nil, source, o, mode, color)
}

// EvalReport is Eval plus the -compile-report surface, a compilation-refusal
// warning stream, and caller-resolved color. When report is non-nil, the
// instance's detached-stamp attribution (lang.Boru.StampReport —
// design/RUNTIME-STAMPING.0.md) is printed to it after the run, one line per
// runtime-constructed callback with its outcome or refusal reason. When warn is
// non-nil and the default compile-try mode falls back because the WHOLE program
// refused to compile, a one-line performance warning naming the refusal reason
// is printed to it (a refusal runs on the slower interpreter). color renders a
// structured BoruError through the ANSI diagnostic renderer; color=false keeps
// the byte-identical plain text.
func EvalReport(w, report, warn io.Writer, source string, o lang.Options, mode CompileMode, color bool) error {
	a, err := langNew(o)
	if err != nil {
		return fmt.Errorf("init error: %s", err)
	}
	registerTerminalBackend(a)
	runErr := runAndPrint(w, warn, a, source, mode, color)
	if report != nil {
		PrintStampReport(report, a.StampReport())
	}
	return runErr
}

// PrintStampReport renders stamp attribution events one per line. An empty
// report still prints a header line so `-compile-report` under -no-compile
// (never armed, nil events) tells the user why it is empty.
func PrintStampReport(w io.Writer, events []lang.StampEvent) {
	if len(events) == 0 {
		fmt.Fprintln(w, "compile-report: no runtime-stamp attempts (interpreter mode, or no runtime-constructed callbacks)")
		return
	}
	for _, ev := range events {
		name := ev.Name
		if name == "" {
			name = "(anonymous fn)"
		}
		where := ""
		if ev.Pos.Row > 0 {
			where = fmt.Sprintf(" @ %d:%d", ev.Pos.Row, ev.Pos.Col)
		}
		if ev.Stamped {
			fmt.Fprintf(w, "compile-report: stamped %s%s\n", name, where)
		} else {
			reason := ev.Reason
			if reason == "" {
				reason = "body refused the stored-fn compile"
			}
			fmt.Fprintf(w, "compile-report: refused %s%s — %s\n", name, where, reason)
		}
	}
}

// runAndPrint executes source on an already-constructed instance (so callers
// that need to configure the instance first — e.g. seed an in-memory file
// system for bundled imports — can do so before running) and prints the
// residual stack exactly as the run subcommand does.
func runAndPrint(w, warn io.Writer, a *lang.Boru, source string, mode CompileMode, color bool) error {
	var result []any
	var err error
	switch mode {
	case CompileForce:
		result, err = a.RunCompiledStrict(source)
	case CompileTry:
		var reason string
		result, _, reason, err = a.RunCompiledReason(source)
		// Post-Stage-J a genuine refusal RETURNS an error instead of the
		// library silently re-running (plan Phase 11, C2). Try-mode's
		// contract is graceful degradation, so the CLI performs the
		// fallback ITSELF — explicitly and visibly: warn once, naming the
		// first offending construct, then interpret. The fallback moved
		// from the library (hidden) to this caller (attributed). It is
		// keyed on the compile_refused CODE, not the reason: under the
		// one-release BORU_COMPILE_FALLBACK=1 hatch the library already ran
		// the source (the reason is still reported for the warning), and a
		// second run would double its effects. Detached fn-unit stamping
		// stays armed across the fallback run (ArmRuntimeStamping) so
		// stored callbacks still earn the VM path — the compiled mode's
		// contract, exactly as the in-library armed fallback behaved.
		if reason != "" && warn != nil {
			fmt.Fprintf(warn, "warning: bytecode compilation refused, ran on the interpreter (slower): %s\n", reason)
		}
		var refused *lang.BoruError
		if errors.As(err, &refused) && refused.Code == "compile_refused" {
			disarm := a.ArmRuntimeStamping()
			result, err = a.RunInterp(source)
			disarm()
		}
	default:
		// -no-compile: the interpreter EXPLICITLY (Stage J flips the public
		// Run to the compiled path; this mode's contract is the tree-walker).
		result, err = a.RunInterp(source)
	}
	if err != nil {
		// An `IO.exit` request passes through UNFLATTENED. Every other
		// error is rendered here into a display string, which is fine for
		// something a driver only prints — but an exit request is something
		// a driver must READ, and `%s` would erase the type errors.As needs.
		// It is also NOT printed and does not print the residual stack:
		// exiting is not failing, including for a non-zero code.
		if _, isExit := lang.ExitCode(err); isExit {
			return err
		}
		// A structured diagnostic re-renders with the ANSI palette when
		// the caller resolved color for the output stream; anything else
		// (and the color-off path) keeps the historical plain text.
		var ae *lang.BoruError
		if color && errors.As(err, &ae) {
			return fmt.Errorf("error: %s", ae.Render(lang.RenderOpts{Color: true}))
		}
		return fmt.Errorf("error: %s", err)
	}

	if len(result) > 0 {
		parts := make([]string, len(result))
		for i, v := range result {
			parts[i] = fmt.Sprint(v)
		}
		fmt.Fprintln(w, strings.Join(parts, " "))
	}
	return nil
}

// Config is the fully-resolved description of a program baked into a
// standalone executable: the entry source, every bundled file import, and the
// engine settings (registry, seed, compile mode, tape options) frozen at build
// time. It is JSON-serialised into the appended payload (self-embed) and
// referenced by the generated main (`--native`).
type Config struct {
	// Source is the entry program's source text.
	Source string `json:"source"`
	// EntryDir is the absolute directory of the entry file at build time. It
	// is the working directory the in-memory file system resolves relative
	// imports against, so the keys in Files (which are absolute paths) match
	// what loadFileModule asks for at run time.
	EntryDir string `json:"entryDir,omitempty"`
	// Files maps absolute path -> file bytes for the entry and every
	// transitively-imported .boru file. Empty when the program imports only
	// built-in boru: modules (which are compiled into the runtime).
	Files map[string][]byte `json:"files,omitempty"`
	// Registry is the registry path baked in (lang.Options.Registry).
	Registry string `json:"registry,omitempty"`
	// Seed is the random seed baked in (lang.Options.Seed).
	Seed int64 `json:"seed,omitempty"`
	// Compile is the bytecode compile-mode baked in.
	Compile CompileMode `json:"compile,omitempty"`
	// OptionsBlob is the raw --options jsonic string baked in, parsed at run
	// time exactly as the run subcommand parses --options.
	OptionsBlob string `json:"optionsBlob,omitempty"`
	// Profile is the permissions profile baked in at build time by
	// `boru build -perms …`, compiled to a policy.Policy in Main.
	//
	// It is a *policy.Profile and NOT a policy.Policy because Policy is an
	// interface and this struct is JSON-marshalled into the executable's
	// trailer; Profile is the flattened, json-tagged form, produced by the
	// same helper the CLI flags use (permsflags.ProfileFromPolicy).
	//
	// SECURITY NOTE, and it must stay in the docs: the trailer is plain
	// JSON behind a magic+length marker with no integrity check, so a baked
	// profile is a strippable DEFAULT, not a boundary against an attacker
	// who holds the binary. It constrains the PROGRAM, which is what a tool
	// author shipping a boru script wants.
	Profile *policy.Profile `json:"profile,omitempty"`
}

// bundledFirst resolves READS from the bundled sources before the host
// filesystem, and passes everything else — writes, mutations, temp files,
// locks, watches, directory ops — straight through to the host by embedding
// it. That split is the point: a built program must not re-read a live file
// in place of the copy it was built from, and must still be able to write to
// the real filesystem (buildrt_test.go's
// TestMainBundledFilesDoNotHideTheHostFilesystem pins the second half).
//
// Only the three read entry points are overridden. Anything the bundle does
// not have falls through unchanged, so a program reading real data files
// behaves exactly as before.
type bundledFirst struct {
	capabilities.FileOps                      // the host
	mem                  capabilities.FileOps // the bundled sources
}

func (b bundledFirst) ReadFile(path string) ([]byte, error) {
	if data, err := b.mem.ReadFile(path); err == nil {
		return data, nil
	}
	return b.FileOps.ReadFile(path)
}

func (b bundledFirst) Stat(path string, follow bool) (capabilities.FileInfo, error) {
	if fi, err := b.mem.Stat(path, follow); err == nil {
		return fi, nil
	}
	return b.FileOps.Stat(path, follow)
}

// Open consults the bundle only for a READ-ONLY open. Any write intent is the
// host's, since the bundle is an immutable snapshot and a write that landed
// there would be discarded at exit — the silent data loss that made the
// original replace-the-filesystem approach untenable.
func (b bundledFirst) Open(path string, opts capabilities.OpenOpts) (capabilities.FileHandle, error) {
	if !opts.Write && !opts.Append && !opts.Create && !opts.Truncate {
		if h, err := b.mem.Open(path, opts); err == nil {
			return h, nil
		}
	}
	return b.FileOps.Open(path, opts)
}

// Main is the entrypoint a standalone executable runs: build lang.Options from
// the baked Config, overlay any bundled files over the host filesystem, run the
// entry source, and map errors to a process exit code.
//
// args reaches the program as IO.args. Both call sites already passed
// os.Args[1:] here and it was discarded, so a built tool could not see its own
// command line — which is not a tool. That was the single largest gap in the
// packaging story: `boru build` produced a binary on $PATH that could not be
// given an argument.
func Main(cfg Config, args []string, _ io.Reader, stdout, stderr io.Writer) int {
	o := lang.Options{Registry: cfg.Registry, Seed: cfg.Seed, ScriptArgs: args,
		// A built tool is a real program: it sees the real environment and
		// gets the truth about its own streams.
		Env: capabilities.OSEnvOps{}, Streams: capabilities.OSStreamProbe{}}
	if cfg.Profile != nil {
		pol, err := policy.CompileProfile(cfg.Profile)
		if err != nil {
			fmt.Fprintf(stderr, "error: baked policy: %s\n", err)
			return 1
		}
		o.Policy = pol
	}
	if cfg.OptionsBlob != "" {
		m, err := lang.ParseOptions(cfg.OptionsBlob)
		if err != nil {
			fmt.Fprintf(stderr, "error: %s\n", err)
			return 1
		}
		if err := lang.ApplyOptions(&o, m); err != nil {
			fmt.Fprintf(stderr, "error: %s\n", err)
			return 1
		}
	}

	a, err := langNew(o)
	if err != nil {
		fmt.Fprintf(stderr, "init error: %s\n", err)
		return 1
	}
	registerTerminalBackend(a)

	if len(cfg.Files) > 0 {
		mem := lang.NewMemFileOps()
		if cfg.EntryDir != "" {
			mem.Cwd = cfg.EntryDir
		}
		for path, data := range cfg.Files {
			mem.Files[path] = data
		}
		// OVERLAY the bundled sources onto the host filesystem — do not
		// REPLACE it. Replacing meant a multi-file built program lost all
		// real file access: reads of real paths failed, and writes went to
		// RAM and were discarded at exit, silently, with exit 0. Single-file
		// builds took a different branch (build.go attaches Files only when
		// there is more than the entry), so the failure was invisible until
		// a program grew a second file.
		//
		// Reads resolve from the BUNDLE first; everything else goes to the
		// host. An overlay cannot express that — its upper layer is both the
		// write target and the first read consulted — so host-upper (writes
		// work, bundle only wins where the host has nothing) and mem-upper
		// (bundle wins, writes trapped in RAM) are both wrong, in opposite
		// directions. bundledFirst splits the two.
		//
		// Host-upper was not merely "not self-contained". Because a relative
		// `import "./lib.boru"` resolves through the file layer against the
		// RUN-TIME process cwd, a built tool started in any directory holding
		// a file of that name loaded and executed THAT file instead of its
		// bundled module. A baked -perms profile constrains what such code
		// may do; it does not stop it running. Both cases are pinned below.
		a.SetFileOps(bundledFirst{FileOps: a.HostFileOps(), mem: mem})
		// Anchor relative imports to the BUILD-TIME entry directory. Without
		// this, resolveImportPath leaves `./lib.boru` relative (it only joins
		// when BaseDir is set), the file layer resolves it against the RUN-TIME
		// process cwd, and the bundle — keyed by build-machine absolute paths —
		// is never consulted at all. bundledFirst alone does not fix that: it
		// decides which layer answers a path, not which path is asked for.
		//
		// With BaseDir set, `./lib.boru` becomes exactly the key the bundle was
		// written under, so the bundled module answers and a same-named file in
		// whatever directory the tool was started from never gets a look in.
		if cfg.EntryDir != "" {
			a.NativeRegistry().BaseDir = cfg.EntryDir
		}
	}

	// warn is nil DELIBERATELY: a built binary must not editorialise about its
	// own execution engine. `boru run` warns when the whole program refused to
	// compile and fell back to the interpreter — that is developer-facing
	// performance advice, and its test pins it — but a shipped tool writing
	// "warning: bytecode compilation refused…" to stderr on every invocation is
	// noise in someone else's pipeline, and the refusals are easy to hit (two
	// statement-form `if (cond) [body]` statements are enough). The user of a
	// tool cannot act on it; the author, running `boru run`, can.
	if err := runAndPrint(stdout, nil, a, cfg.Source, cfg.Compile, lang.ResolveColor(a.NativeRegistry(), stderr, "auto")); err != nil {
		if code, isExit := lang.ExitCode(err); isExit {
			return code
		}
		fmt.Fprintf(stderr, "%s\n", err)
		return 1
	}
	return 0
}

// magic marks the trailer of a self-embedding executable and is the only
// trailer this binary WRITES. It is intentionally unlikely to occur in a
// vanilla binary's tail. Every trailer this binary can READ comes from
// wire.ExecMagics(), which includes the ones earlier, differently-named
// releases wrote.
var magic = []byte(wire.ExecMagic)

// Footer layout appended after the JSON payload: the magic followed by the
// payload length as a big-endian uint64. The magics differ in LENGTH across
// releases ("VLTEXEC\x01" and "AQLEXEC\x01" are 8 bytes, "BORUEXEC\x01" is
// 9), so the length field's offset is derived from whichever magic matched —
// never from len(magic). Assuming a fixed magic size is what silently
// orphaned every executable built before the AQL -> BORU rename.
const lenSize = 8

// footerSize is the trailer this binary writes.
var footerSize = len(magic) + lenSize

// maxFooterSize bounds the tail read that detection needs in order to test
// every readable magic, longest first.
var maxFooterSize = func() int {
	max := 0
	for _, m := range wire.ExecMagics() {
		if len(m) > max {
			max = len(m)
		}
	}
	return max + lenSize
}()

// matchFooter finds which readable magic terminates image (immediately
// before the 8-byte length field) and returns the full footer size for it.
func matchFooter(tail []byte) (int, bool) {
	n, ok := wire.MatchSuffix(tail, wire.ExecMagics(), lenSize)
	if !ok {
		return 0, false
	}
	return n + lenSize, true
}

// EncodePayload returns the bytes to append to a copied host binary: the
// JSON-encoded Config followed by the fixed trailer (magic + 8-byte big-endian
// payload length). Detection reads the trailer from the end of the file.
// jsonMarshal is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive EncodePayload's marshal-failure arm, which is unreachable with
// the plain Config shape.
var jsonMarshal = json.Marshal

func EncodePayload(cfg Config) ([]byte, error) {
	body, err := jsonMarshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("encode payload: %w", err)
	}
	footer := make([]byte, footerSize)
	copy(footer[:len(magic)], magic)
	binary.BigEndian.PutUint64(footer[len(magic):], uint64(len(body)))
	return append(body, footer...), nil
}

// DecodePayload extracts the embedded Config from a binary's raw bytes. ok is
// false (with a nil error) when the trailer magic is absent — i.e. this is a
// plain boru binary, not a built executable. A present-but-corrupt trailer
// returns an error.
func DecodePayload(image []byte) (cfg Config, ok bool, err error) {
	if len(image) < lenSize {
		return Config{}, false, nil
	}
	fs, ok := matchFooter(image)
	if !ok {
		return Config{}, false, nil
	}
	n := binary.BigEndian.Uint64(image[len(image)-lenSize:])
	end := len(image) - fs
	if uint64(end) < n {
		return Config{}, false, fmt.Errorf("embedded payload: length %d exceeds image", n)
	}
	body := image[end-int(n) : end]
	if err := json.Unmarshal(body, &cfg); err != nil {
		return Config{}, false, fmt.Errorf("embedded payload: %w", err)
	}
	return cfg, true, nil
}

// fileStat is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive ReadEmbeddedPayload's stat-failure arm — Stat on a freshly
// opened local file does not fail on a healthy host.
var fileStat = (*os.File).Stat

// fileReadAt is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// drive ReadEmbeddedPayload's read-failure arms, which the preceding
// size checks make unreachable with real files.
var fileReadAt = (*os.File).ReadAt

// ReadEmbeddedPayload returns the embedded Config if exePath is a built
// executable. ok is false (nil error) for a plain boru binary. Only the trailing
// footer is read first, and the payload only when the magic matches — so the
// common case (a stock boru binary, checked on every CLI invocation) costs a
// small tail read, not a full scan of the multi-megabyte binary.
func ReadEmbeddedPayload(exePath string) (cfg Config, ok bool, err error) {
	f, err := os.Open(exePath)
	if err != nil {
		return Config{}, false, fmt.Errorf("read self: %w", err)
	}
	defer f.Close()

	info, err := fileStat(f)
	if err != nil {
		return Config{}, false, fmt.Errorf("read self: %w", err)
	}
	size := info.Size()
	if size < int64(lenSize) {
		return Config{}, false, nil
	}

	// Read enough tail to test the longest readable magic; a shorter one
	// simply matches further into the buffer.
	want := int64(maxFooterSize)
	if want > size {
		want = size
	}
	tail := make([]byte, want)
	if _, err := fileReadAt(f, tail, size-want); err != nil {
		return Config{}, false, fmt.Errorf("read self: %w", err)
	}
	fs, ok := matchFooter(tail)
	if !ok {
		return Config{}, false, nil
	}

	n := int64(binary.BigEndian.Uint64(tail[len(tail)-lenSize:]))
	if n < 0 || n > size-int64(fs) {
		return Config{}, false, fmt.Errorf("embedded payload: length %d exceeds image", n)
	}
	body := make([]byte, n)
	if _, err := fileReadAt(f, body, size-int64(fs)-n); err != nil {
		return Config{}, false, fmt.Errorf("embedded payload: %w", err)
	}
	if err := json.Unmarshal(body, &cfg); err != nil {
		return Config{}, false, fmt.Errorf("embedded payload: %w", err)
	}
	return cfg, true, nil
}

// AbsDir returns the absolute directory of a file path, for keying bundled
// files and setting the in-memory working directory consistently.
func AbsDir(file string) (string, error) {
	abs, err := filepath.Abs(file)
	if err != nil {
		return "", err
	}
	return filepath.Dir(abs), nil
}
