// Shared spec fixtures: the word registry, tokenizer, and .tsv corpus
// loader used by BOTH the interpreter spec gate (spec.test.ts) and the
// compiled differential gate (corpus.test.ts). Extracted verbatim from the
// original spec.test.ts so the two gates run the identical fixture set.

import type { EmitState } from './emit.ts'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

import { canon } from '@boru-lang/core'
import { parse } from '@boru-lang/parser'
import { mintNamedType, resolveWordsDeep, typeContentOf } from '@boru-lang/core'
import {
  coerceBoolean,
  isRecordShape,
  isTypeBody,
  isValueOfType,
  pathOf,
  typeOf,
} from '@boru-lang/core'
import { makeIdealHandler, makeScalarHandler, makeScalarOptsHandler } from '@boru-lang/core'
import {
  BoruError,
  type BoruType,
  Engine,
  type Handler,
  type NativeFunc,
  Registry,
  TAny,
  TAtom,
  TBoolean,
  TInteger,
  TNever,
  TNone,
  TNumber,
  TString,
  TList,
  TMap,
  TIdeal,
  TNode,
  TClass,
  TDisjunct,
  TScalar,
  TType,
  TWord,
  Value,
  builtinRank,
  type FnParam,
  type FnSig,
  newAtom,
  newBoolean,
  newDynamicCarrier,
  newDisjunct,
  newEnum,
  newFnDef,
  newFnUndef,
  newFloat,
  newInspect,
  newInteger,
  newList,
  newMap,
  newMark,
  newMove,
  newNone,
  newClassType,
  ClassTypeInfo,
  newString,
  OrderedMap,
  newErrorValue,
  newTypeLiteral,
  newWord,
  withQuoted,
  typeNameTable,
} from './index.ts'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const SPEC_DIR = path.resolve(__dirname, '..', '..', 'spec')

// Counter for unique mark IDs generated by `replay`.
let replayCounter = 0

// Bare type-name → Type lookup, used by the tokenizer to resolve
// uppercase type words (Integer, List, …) to type literals.
const typeTable = typeNameTable()

/**
 * Recover the concrete value a compile-mode operand will hold at run time, so
 * a constraint can be validated statically. In compile mode a literal is
 * stripped to a carrier and a `quote …` operand becomes a self-contained
 * island; neither is `isConcrete()`, but both are determinable:
 *   - a stripped literal / inert container → its const original via classify;
 *   - a 0-input token island (`quote red`, `quote [1 2 3]`) → the value it
 *     re-runs to, evaluated on a throwaway non-check registry (islands are
 *     capture-free, so a fresh registry reproduces the result faithfully).
 * Returns null when the value cannot be determined at compile time.
 */
function recoverConcrete(emit: import('./emit.ts').EmitState, value: Value): Value | null {
  if (value.isConcrete()) return value
  const op = emit.classify(value)
  if (op !== null && op.kind === 'const') return op.value
  const island = emit.islandTokensFor(value)
  if (island !== null) {
    try {
      const tmp = new Registry()
      registerSpecWords(tmp)
      const out = new Engine(tmp).run([...island])
      if (out.length === 1 && out[0]!.isConcrete()) return out[0]!
    } catch {
      /* fall through to null — caller refuses */
    }
  }
  return null
}

/**
 * Apply a `def`/`enum` type constraint to a value. Three modes:
 *   - Interpret mode: throw the canonical `type_error` on violation (the
 *     long-standing runtime behaviour).
 *   - Compile mode (an active EmitState): validate against the recovered
 *     concrete value. A violation lowers to a terminal `OpTrap` so the compiled
 *     program raises the byte-identical `type_error` the interpreter would
 *     (mirrors Go's check-lenient/run-error parity); a value the compiler
 *     cannot determine statically refuses, falling back to the interpreter.
 *   - Pure check mode (no EmitState): lenient — the value may be a type-only
 *     carrier, so the constraint is never evaluated (unchanged behaviour).
 * Returns true when the caller must ABORT the bind (the violation was handled
 * via trap/refuse), false to proceed with the bind.
 */
function enforceTypeConstraint(
  registry: Registry,
  value: Value,
  constraint: Value,
  detail: string,
  word: string,
): boolean {
  // Post-opacity, a constraint can carry bare type-name Words
  // (`[:Integer]` arrives with child word(Integer)) — resolve them
  // through the canonical cascade before validating.
  constraint = resolveWordsDeep(constraint, registry)
  const emit = registry.check.emit as EmitState | undefined
  if (registry.check.isActive()) {
    if (emit === undefined) return false // pure check mode: lenient
    const concrete = recoverConcrete(emit, value)
    if (concrete === null) {
      emit.markUncompilable('def: unverifiable type constraint on a computed value')
      return true
    }
    if (!isValueOfType(concrete, constraint)) {
      if (!emit.recordTrap('type_error', detail, word)) {
        emit.markUncompilable('def: conditional type-constraint violation')
      }
      return true
    }
    return false
  }
  // Interpret mode.
  if (!isValueOfType(value, constraint)) throw new BoruError('type_error', detail, word)
  return false
}

function registerSpecWords(r: Registry): void {
  const intHandler =
    (op: (a: bigint, b: bigint) => bigint): Handler =>
    (args) =>
      [newInteger(op(args[0]!.asInteger(), args[1]!.asInteger()))]

  const reg = (fn: NativeFunc): void => r.registerNativeFunc(fn)

  reg({
    name: 'add',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a + b) }],
  })
  reg({
    name: 'sub',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a - b) }],
  })
  reg({
    name: 'mul',
    forwardPrecedence: true,
    signatures: [{ args: [TInteger, TInteger], handler: intHandler((a, b) => a * b) }],
  })
  reg({
    name: 'neg',
    signatures: [
      {
        args: [TInteger],
        handler: (args) => [newInteger(-args[0]!.asInteger())],
      },
    ],
  })
  reg({
    name: 'dup',
    signatures: [
      {
        args: [TAny],
        handler: (args) => [args[0]!, args[0]!],
        returns: [TAny, TAny],
      },
    ],
  })
  reg({
    name: 'swap',
    signatures: [
      {
        args: [TAny, TAny],
        // Under the unified §1.4 dispatch rule, args[0] is the top
        // of the stack and args[1] is the next-deeper. The splice
        // writes the handler's return slice in source order, so
        // returning [args[0], args[1]] places the old top at the
        // deeper position and the old next-deeper at the top — the
        // two values come out swapped on the stack.
        handler: (args) => [args[0]!, args[1]!],
        returns: [TAny, TAny],
      },
    ],
  })
  reg({
    name: 'drop',
    signatures: [
      {
        args: [TAny],
        handler: () => [],
        returns: [],
      },
    ],
  })
  reg({
    name: 'concat',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString, TString],
        handler: (args) => [newString(args[0]!.asString() + args[1]!.asString())],
      },
    ],
  })
  // not / and / or — Boolean sigs plus an Any-coercing fallback,
  // mirroring registerEngSpecBoolean (CoerceBoolean).
  const notH: Handler = (args) => [newBoolean(!coerceBoolean(args[0]!))]
  const andH: Handler = (args) => [coerceBoolean(args[1]!) ? args[0]! : args[1]!]
  const orH: Handler = (args) => [coerceBoolean(args[1]!) ? args[1]! : args[0]!]
  reg({
    name: 'not',
    forwardPrecedence: true,
    signatures: [{ args: [TBoolean], handler: notH }, { args: [TAny], handler: notH }],
  })
  reg({
    name: 'and',
    forwardPrecedence: true,
    signatures: [
      { args: [TBoolean, TBoolean], handler: andH },
      { args: [TAny, TAny], handler: andH },
    ],
  })
  reg({
    name: 'or',
    signatures: [
      { args: [TBoolean, TBoolean], barrierPos: 1, handler: orH },
      { args: [TAny, TAny], barrierPos: 1, handler: orH },
    ],
  })
  reg({
    name: 'describe',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        handler: (args) => [newString(`int:${args[0]!.asInteger().toString()}`)],
      },
      {
        args: [TString],
        handler: (args) => [newString(`str:${args[0]!.asString()}`)],
      },
    ],
  })
  reg({
    name: 'tag',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny],
        handler: () => [newString('any')],
      },
      {
        args: [TInteger],
        handler: () => [newString('specific')],
      },
    ],
  })

  // fact, code, route: §1.1 literal-pattern dispatch via patterns.
  // Each declares a specific-value overload first plus a catch-all.
  reg({
    name: 'fact',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        patterns: new Map([[0, newInteger(0n)]]),
        handler: () => [newInteger(1n)],
      },
      {
        args: [TInteger],
        handler: (args) => [newInteger(args[0]!.asInteger())],
      },
    ],
  })
  reg({
    name: 'code',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger],
        patterns: new Map([[0, newInteger(99n)]]),
        handler: () => [newString('ninety-nine')],
      },
      {
        args: [TInteger],
        handler: () => [newString('general')],
      },
    ],
  })
  reg({
    name: 'route',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString],
        patterns: new Map([[0, newString('admin')]]),
        handler: () => [newString('matched-admin')],
      },
      {
        args: [TString],
        handler: () => [newString('other')],
      },
    ],
  })

  // trip: 3-arg integer formatter. Default barrier = N so all
  // position-mixing arrangements (all-forward through all-stack)
  // bind sig[0..2] to the same source-order args.
  reg({
    name: 'trip',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger, TInteger],
        handler: (args) =>
          [newString(
            `${args[0]!.asInteger().toString()},${args[1]!.asInteger().toString()},${args[2]!.asInteger().toString()}`,
          )],
      },
    ],
  })

  // pair: mixed-barrier sig [Integer | Integer]. Forward fills
  // sig[0]; sig[1] must come from the stack. The handler formats
  // "args[0]:args[1]" so the binding is visible in the output.
  reg({
    name: 'pair',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger],
        barrierPos: 1,
        handler: (args) =>
          [newString(`${args[0]!.asInteger().toString()}:${args[1]!.asInteger().toString()}`)],
      },
    ],
  })

  // length, first: list-aware test words for list.tsv.
  reg({
    name: 'length',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => [newInteger(BigInt(args[0]!.asList().length))],
      },
    ],
  })
  reg({
    name: 'first',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => {
          const lst = args[0]!.asList()
          if (lst.length === 0) return [newNone()]
          return [lst[0]!]
        },
      },
    ],
  })

  // ── Forth-style stack manipulators (stack.tsv) ───────────────────
  // All stack-only (barrierPos 0): args[0] is the top, args[1] the
  // next-deeper, etc. The handler returns the splice-form replacement
  // in source order. Mirrors registerEngSpecStack. (dup/swap/drop are
  // registered above; the rest are added here.)
  const stackOp = (name: string, argCount: number, fn: (a: Value[]) => Value[]): void => {
    // Probe the handler to learn its TRUE result count so the checker models
    // the arity faithfully (Go annotates these via NativeSig.Returns). A
    // non-1 count makes the bytecode recorder refuse (multi/zero-result) and
    // fall back; a 1-result reorder (nip) stays compilable.
    const returns = fn(new Array<Value>(argCount).fill(newNone())).map(() => TAny)
    reg({
      name,
      signatures: [
        { args: new Array<typeof TAny>(argCount).fill(TAny), barrierPos: 0, handler: (a) => fn(a), returns },
      ],
    })
  }
  stackOp('over', 2, (a) => [a[1]!, a[0]!, a[1]!])
  stackOp('rot', 3, (a) => [a[1]!, a[0]!, a[2]!])
  stackOp('nip', 2, (a) => [a[0]!])
  stackOp('tuck', 2, (a) => [a[0]!, a[1]!, a[0]!])
  stackOp('dup2', 2, (a) => [a[1]!, a[0]!, a[1]!, a[0]!])
  stackOp('swap2', 4, (a) => [a[1]!, a[0]!, a[3]!, a[2]!])
  stackOp('drop2', 2, () => [])
  stackOp('over2', 4, (a) => [a[3]!, a[2]!, a[1]!, a[0]!, a[3]!, a[2]!])

  // ── q-suffixed fixtures (barrier.tsv, numbers.tsv, typeof.tsv, …) ──
  // These mirror test/go/engspec/engspec_test.go::registerSpecWords.
  // The eng/spec corpus references the q-suffixed names so they don't
  // collide with any production word set.
  const toFloat = (v: Value): number =>
    v.vType.matches(TInteger) ? Number(v.asInteger()) : v.asFloat()
  const numericBinary =
    (intOp: (a: bigint, b: bigint) => bigint, floatOp: (a: number, b: number) => number): Handler =>
    (args) => {
      if (args[0]!.vType.matches(TInteger) && args[1]!.vType.matches(TInteger)) {
        return [newInteger(intOp(args[0]!.asInteger(), args[1]!.asInteger()))]
      }
      return [newFloat(floatOp(toFloat(args[0]!), toFloat(args[1]!)))]
    }
  const numberPair = [TNumber, TNumber]

  reg({
    name: 'addq',
    forwardPrecedence: true,
    signatures: [{ args: numberPair, handler: numericBinary((a, b) => b + a, (a, b) => b + a) }],
  })
  reg({
    name: 'subq',
    forwardPrecedence: true,
    signatures: [{ args: numberPair, handler: numericBinary((a, b) => b - a, (a, b) => b - a) }],
  })
  reg({
    name: 'mulq',
    forwardPrecedence: true,
    signatures: [{ args: numberPair, handler: numericBinary((a, b) => b * a, (a, b) => b * a) }],
  })
  reg({
    name: 'negq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TNumber],
        barrierPos: 1,
        handler: (args) =>
          args[0]!.vType.matches(TInteger)
            ? [newInteger(-args[0]!.asInteger())]
            : [newFloat(-args[0]!.asFloat())],
      },
    ],
  })
  reg({
    name: 'concatq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TString, TString],
        handler: (args) => [newString(args[1]!.asString() + args[0]!.asString())],
      },
    ],
  })
  reg({
    name: 'describeq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], handler: (args) => [newString(`int:${args[0]!.asInteger()}`)] },
      { args: [TString], handler: (args) => [newString(`str:${args[0]!.asString()}`)] },
    ],
  })
  reg({
    name: 'tagq',
    forwardPrecedence: true,
    signatures: [
      { args: [TAny], handler: () => [newString('any')] },
      { args: [TInteger], handler: () => [newString('specific')] },
    ],
  })
  reg({
    name: 'factq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], patterns: new Map([[0, newInteger(0n)]]), handler: () => [newInteger(1n)] },
      { args: [TInteger], handler: (args) => [newInteger(args[0]!.asInteger())] },
    ],
  })
  reg({
    name: 'codeq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], patterns: new Map([[0, newInteger(99n)]]), handler: () => [newString('ninety-nine')] },
      { args: [TInteger], handler: () => [newString('general')] },
    ],
  })
  reg({
    name: 'routeq',
    forwardPrecedence: true,
    signatures: [
      { args: [TString], patterns: new Map([[0, newString('admin')]]), handler: () => [newString('matched-admin')] },
      { args: [TString], handler: () => [newString('other')] },
    ],
  })
  reg({
    name: 'tripq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger, TInteger],
        handler: (args) =>
          [newString(`${args[0]!.asInteger()},${args[1]!.asInteger()},${args[2]!.asInteger()}`)],
      },
    ],
  })
  reg({
    name: 'pairq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TInteger, TInteger],
        barrierPos: 1,
        handler: (args) => [newString(`${args[0]!.asInteger()}:${args[1]!.asInteger()}`)],
      },
    ],
  })
  // nilq — a 0-arg word (barrier 0).
  reg({
    name: 'nilq',
    signatures: [{ args: [], barrierPos: 0, handler: () => [newString('nil')] }],
  })
  // flexq — two forward-eligible overloads of arity 1 and 2.
  reg({
    name: 'flexq',
    forwardPrecedence: true,
    signatures: [
      { args: [TInteger], handler: (args) => [newString(`one:${args[0]!.asInteger()}`)] },
      {
        args: [TInteger, TInteger],
        handler: (args) => [newString(`two:${args[0]!.asInteger()},${args[1]!.asInteger()}`)],
      },
    ],
  })
  // Fixed-arity Integer formatters with an intrinsic barrier at the
  // numeric-suffix position; handler renders args in sig order.
  const intArgsFmt: Handler = (args) =>
    [newString(args.map((a) => a.asInteger().toString()).join(','))]
  const intArity = (name: string, n: number, barrier: number): void => {
    reg({
      name,
      forwardPrecedence: true,
      signatures: [{ args: new Array<typeof TInteger>(n).fill(TInteger), barrierPos: barrier, handler: intArgsFmt }],
    })
  }
  intArity('tri1q', 3, 1)
  intArity('tri2q', 3, 2)
  intArity('quad1q', 4, 1)
  intArity('quadq', 4, 2)
  intArity('quad3q', 4, 3)
  intArity('quintq', 5, 3)
  intArity('hexq', 6, 3)
  intArity('septq', 7, 4)
  reg({
    name: 'lengthq',
    forwardPrecedence: true,
    signatures: [{ args: [TList], handler: (args) => [newInteger(BigInt(args[0]!.asList().length))] }],
  })
  reg({
    name: 'firstq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        handler: (args) => {
          const lst = args[0]!.asList()
          return lst.length === 0 ? [newNone()] : [lst[0]!]
        },
      },
    ],
  })
  reg({
    name: 'replayq',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // replayq emits mark/move tape tokens the stack VM has no opcodes for;
        // island it (bake the inert body, re-run through a sub-engine that
        // handles the replay). A non-inert body (paren/nested) falls back.
        compileFallback: true,
        handler: (args) => {
          const body = args[0]!.asList()
          replayCounter++
          const id = `__replayq_${replayCounter}`
          return [newMark(id, [...body]), ...body, newMove(id)]
        },
      },
    ],
  })

  // do — evaluate a list body in a sub-engine, or deep-evaluate the
  // list-valued slots of a map. Mirrors registerEngSpecDo. The arg
  // arrives unevaluated (noEvalArgs); a bare List/Map type literal fails
  // the concrete-container match and surfaces a signature_error.
  const doEvalMapValue = (v: Value): Value => {
    const emit = r.check.emit
    if (v.isMap() && v.data instanceof OrderedMap) {
      const src = v.asMap()
      const keys = src.keys()
      const vals = keys.map((k) => doEvalMapValue(src.get(k)!))
      if (emit !== undefined) {
        // Compile mode: record a makeMap so the assembled map has provenance.
        const ops = vals.map((x) => emit.classify(x))
        if (ops.every((o) => o !== null)) return emit.recordMakeMap([...keys], ops as import('./emit.ts').Operand[])
        emit.markUncompilable('do-map: value of unknown provenance')
      }
      const out = new OrderedMap()
      keys.forEach((k, i) => out.set(k, vals[i]!))
      return newMap(out)
    }
    if (v.vType.matches(TList) && Array.isArray(v.data)) {
      const residual = new Engine(r).run([...v.asList()])
      // A single-value residual collapses to that value (already provenance-
      // carrying); a multi-value residual is a list — record a makeList.
      if (residual.length === 1) return residual[0]!
      if (emit !== undefined) {
        const ops = residual.map((x) => emit.classify(x))
        if (ops.every((o) => o !== null)) return emit.recordMakeList(ops as import('./emit.ts').Operand[])
        emit.markUncompilable('do-list: element of unknown provenance')
      }
      return newList(residual, { eval: false })
    }
    return v
  }
  reg({
    name: 'do',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TMap],
        noEvalArgs: new Set([0]),
        // Transparent in check mode: doEvalMapValue records makeMap/makeList
        // so a deep-evaluated map (do { a:(1 addq 2) }) compiles.
        runInCheckMode: true,
        handler: (args) => [doEvalMapValue(args[0]!)],
      },
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // runInCheckMode makes `do` TRANSPARENT to the recorder: its body
        // runs in a sub-engine that records into the shared trace, and the
        // body residual (carriers with provenance) becomes do's result — so
        // `do [1 addq 2]` compiles inline with no do-event, exactly like a
        // fn body. In value mode the same handler just runs the body.
        runInCheckMode: true,
        // The escape hatch: a body error surfaces as an Error VALUE
        // rather than propagating — the Go fixture (and basic's
        // production do) is the reference.
        handler: (args) => {
          try {
            return new Engine(r).run([...args[0]!.asList()])
          } catch (e) {
            return [newErrorValue(e instanceof Error ? stripCodePrefix(e.message) : String(e))]
          }
        },
      },
    ],
  })

  // make — scalar coercion. The eng/spec make.tsv rows exercise the
  // scalar targets (String/Integer/Number/Float/Boolean/Atom). The
  // [Scalar, Any] sig with typeArgs on arg0 forces a type-literal
  // target. Class/Options overloads are added by a later increment.
  // Mirrors registerEngSpecMake (scalar slice).
  reg({
    name: 'make',
    forwardPrecedence: true,
    signatures: [
      { args: [TScalar, TMap, TAny], typeArgs: new Set([0]), handler: (a) => makeScalarOptsHandler(a) },
      { args: [TAny, TAny, TMap], handler: () => unsupportedMake('with-opts') },
      { args: [TIdeal, TMap], typeArgs: new Set([0]), handler: (a) => makeIdealHandler(a) },
      { args: [TScalar, TAny], typeArgs: new Set([0]), handler: (a) => makeScalarHandler(a) },
      {
        args: [TAny, TAny],
        handler: (a) => {
          // An UNRESOLVED word target (`make Path 'a/b'` — no such type
          // name) is the undefined-word error, matching the Go engine
          // where the bare word steps and fails before make dispatches.
          const t0 = a[0]!
          if (t0.isWord()) {
            throw new BoruError('undefined_word', `undefined word: ${t0.asWord().name}`, t0.asWord().name)
          }
          return unsupportedMake('generic')
        },
      },
    ],
  })
  // get / set — kernel-container signatures (the handlers cover the
  // Node map/list case; their full sig list is what inspect renders).
  // Mirrors registerEngSpecStorage.
  // stripCodePrefix drops the `[boru/<code>]: ` render prefix so a
  // caught Error VALUE carries the bare detail, matching Go's
  // ErrorInfo.Message.
  const stripCodePrefix = (msg: string): string => msg.replace(/^\[[^\]]*\]:\s*/, '')
  // Misses return the None TYPE LITERAL, not the none value — the Go
  // fixture (registerEngSpecStorage) is the reference.
  const getNodeH: Handler = (args) => {
    const key = args[0]!
    const c = args[1]!
    if (key.vType.matches(TInteger) && Array.isArray(c.data)) {
      const i = Number(key.asInteger())
      const lst = c.asList()
      return [i >= 0 && i < lst.length ? lst[i]! : newTypeLiteral(TNone)]
    }
    if (c.data instanceof OrderedMap) {
      const k = key.vType.equal(TAtom) ? key.asAtom() : key.asString()
      const v = c.asMap().get(k)
      return [v ?? newTypeLiteral(TNone)]
    }
    return [newTypeLiteral(TNone)]
  }
  reg({
    name: 'get',
    signatures: [
      { args: [TString, TClass], barrierPos: 1, handler: getNodeH },
      { args: [TString, TNode], barrierPos: 1, handler: getNodeH },
      { args: [TInteger, TClass], barrierPos: 1, handler: getNodeH },
      { args: [TInteger, TNode], barrierPos: 1, handler: getNodeH },
      { args: [TAtom, TClass], barrierPos: 1, quoteArgs: new Set([0]), handler: getNodeH },
      { args: [TAtom, TNode], barrierPos: 1, quoteArgs: new Set([0]), handler: getNodeH },
      { args: [TAny, TNone], barrierPos: 1, handler: () => [newTypeLiteral(TNone)] },
    ],
  })
  reg({
    name: 'set',
    forwardPrecedence: true,
    signatures: [
      { args: [TString, TAny, TClass], handler: () => unsupportedMake('set') },
      { args: [TAtom, TAny, TClass], handler: () => unsupportedMake('set') },
    ],
  })
  // refine — the uniform type constructor (its sig list is what inspect
  // renders; structural construction is a follow-up).
  reg({
    name: 'refine',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny, TNode],
        noEvalArgs: new Set([1]),
        // Build the record/object type in check mode so typeof/is/inspect
        // consume it and it bakes as an inert type constant.
        runInCheckMode: true,
        handler: (args) => {
          const base = args[0]!
          // refine Record [ {k:T} … ] merges the pair-maps into a
          // record-shape map.
          if (base.data === null && base.vType.leaf() === 'Record' && Array.isArray(args[1]!.data)) {
            const elems = args[1]!.asList()
            if (0 === elems.length) {
              throw new BoruError('type_error', 'record: list must have at least one field', 'refine')
            }
            const om = new OrderedMap()
            for (const pair of elems) {
              if (!(pair.data instanceof OrderedMap)) {
                throw new BoruError(
                  'type_error',
                  `record: each element must be a pair (map), got ${pair.toString()}`,
                  'refine',
                )
              }
              const m = pair.asMap()
              for (const k of m.keys()) om.set(k, m.get(k)!)
            }
            return [newMap(om)]
          }
          // class {field:Type …} — a fresh class type with the base
          // Class as parent. refine Base {…} extends an existing class
          // type, inheriting its fields. The struct name is empty until
          // a `def Name …` binding stamps it.
          if (base.data === null && base.vType.leaf() === 'Class' && args[1]!.isMap()) {
            return [buildClassType('Class', new OrderedMap(), args[1]!)]
          }
          if (base.data instanceof ClassTypeInfo && args[1]!.isMap()) {
            return [buildClassType(base.data.path, base.data.fields, args[1]!)]
          }
          return unsupportedMake('refine')
        },
      },
      {
        args: [TAny],
        runInCheckMode: true,
        // The 1-arg bare form: return the base type unchanged (the
        // paired def mints the fresh subtype) — the Go fixture's
        // refineBareCtorH is the reference. A non-type argument is the
        // same error, message-for-message.
        handler: (args) => {
          const base = args[0]!
          const isTypeBody =
            base.data === null ||
            base.data instanceof ClassTypeInfo ||
            (base.data instanceof OrderedMap && base.vType.leaf() === 'Map')
          if (!isTypeBody) {
            throw new BoruError('type_error', `refine: argument must be a type, got ${base.toString()}`, 'refine')
          }
          return [base]
        },
      },
    ],
  })

  // inspect — render a word's signatures or a type's structure as an
  // inspection map. Mirrors registerEngSpecInspect (buildInspection /
  // buildTypeInspection). The word form fires when the arg is a Word
  // naming a registered native; otherwise the type form runs.
  reg({
    name: 'inspect',
    forwardPrecedence: true,
    signatures: [
      {
        // Word form: the Atom quoteArgs slot captures the name as data
        // (so the matcher does not dispatch a registered word like `dup`).
        args: [TAtom],
        quoteArgs: new Set([0]),
        recordsOwnEvent: true,
        // Island [inspect <name>] when the name is NOT a def: a registered
        // word's signatures and an unknown name's "unknown" inspection are
        // both registry-stable, so the island re-runs faithfully. A def's
        // binding is compile-time only (not live in the VM) — refuse it.
        returnsFn: (args, registry) => {
          const out = newDynamicCarrier(TMap)
          const emit = registry.check.emit as EmitState | undefined
          if (emit !== undefined) {
            const a = args[0]!
            const name = a.isWord() ? a.asWord().name : a.data !== null ? a.asAtom() : ''
            const top = name === '' ? undefined : registry.topOfDefStack(name)
            if (name === '') {
              // The operand is a computed VALUE (e.g. `inspect (quote red)`),
              // not a name. Thread it into an inspect island that re-runs the
              // identical dispatch on the runtime value — matches by
              // construction. Refuses if the operand has no provenance.
              if (!emit.recordFallback('inspect', [a], [out], registry)) {
                emit.markUncompilable('inspect: non-name operand of unknown provenance')
              }
            } else if (top === undefined) {
              // Registered word or unknown name: registry-stable, island it.
              emit.recordTokenIsland([newWord('inspect'), newWord(name)], out, 'inspect')
            } else {
              // A def bound to a compile-time-known value (a type / enum /
              // sig / fn, or a literal recovered through its carrier): its
              // inspection is fixed, so bake the precomputed result.
              let concrete: import('@boru-lang/core').Value | null = top.carrier ? null : top
              if (concrete === null) {
                concrete = emit.constValueOf(emit.classify(top))
              }
              if (concrete !== null) {
                emit.recordTokenIsland(
                  [buildDefinedInspection(name, resolveWordsDeep(typeContentOf(concrete), registry))],
                  out,
                  'inspect',
                )
              } else {
                emit.markUncompilable('inspect: def bound to a computed value')
              }
            }
          }
          return [out]
        },
        handler: (args, _ctx, _stk, registry) => {
          const name = args[0]!.asAtom()
          const fn = registry.lookup(name)
          if (fn) return [buildWordInspection(name, fn)]
          const top = registry.topOfDefStack(name)
          // A named type's inspection is its content's (Stage 2: the def
          // binds the node, which carries the declared shape).
          if (top !== undefined) return [buildDefinedInspection(name, resolveWordsDeep(typeContentOf(top), registry))]
          // Post-opacity a captured type NAME arrives as this Atom —
          // resolve through the builtin arm of the cascade so
          // `inspect Any` reports the type literal, not "unknown".
          const t = typeNameTable().get(name)
          if (t !== undefined) return [buildTypeInspection(newTypeLiteral(t))]
          const unk = new OrderedMap()
          unk.set('name', newString(name))
          unk.set('kind', newWord('unknown'))
          unk.set('signatures', newList([], { eval: false }))
          return [newInspect(unk)]
        },
      },
      {
        args: [TAny],
        handler: (args, _ctx, _stk, registry) => [buildTypeInspection(resolveWordsDeep(args[0]!, registry))],
      },
    ],
  })

  // word VALUE — wraps an (unevaluated) value as a code body. In this
  // TS subset an unquoted list bound via def already splices its
  // elements at the use site (Engine.stepWord path 2), so `word` is the
  // identity that defers evaluation of its argument. Mirrors the Go
  // `word`/__SP splice fixture for forth.tsv.
  reg({
    name: 'word',
    forwardPrecedence: true,
    // runInCheckMode so the word-body list is produced in the record pass and
    // bound by def; a later reference splices the body inline, which records
    // its events (the macro is transparent to the recorder, like do/def).
    signatures: [
      { args: [TAny], noEvalArgs: new Set([0]), runInCheckMode: true, handler: (args) => [args[0]!] },
    ],
  })

  // def: spec-subset code-body binding. Captures `def NAME body`
  // where NAME arrives as a Word token (no /q machinery in this
  // runner's tokenizer) and body is any value — typically a List
  // literal that becomes a callable code body. The handler pushes
  // the body onto the def stack under NAME.
  reg({
    name: 'def',
    forwardPrecedence: true,
    signatures: [
      // `def name word BODY` — the Forth-style splice binder. `word` is
      // a KEYWORD SLOT (quoted, pattern-matched), so def captures it
      // structurally instead of stranding on it under the strict
      // forward-barrier. Mirrors the Go engspec fixture's defWord; the
      // TS def-substitution already splices an unquoted eval-list body
      // at each reference, so binding the raw body IS the splice.
      {
        args: [TAtom, TAtom, TAny],
        quoteArgs: new Set([0, 1]),
        patterns: new Map([[1, newAtom('word')]]),
        noEvalArgs: new Set([2]),
        runInCheckMode: true,
        returns: [],
        handler: (args, _ctx, _stk, registry) => {
          const nameArg = args[0]!
          const name = nameArg.isWord() ? nameArg.asWord().name : nameArg.asAtom()
          if (/^-?\d/.test(name)) {
            throw new BoruError('syntax_error', `invalid numeric literal: ${name}`, name)
          }
          registry.check.recordDef(name)
          registry.pushDef(name, args[2]!)
          return []
        },
      },
      // `def name fn [triples]` — the fn KEYWORD SLOT. Captures `fn`
      // structurally and binds the FnDef by name, mirroring the Go
      // fixture's defFn. Without it, `def name fn […]` strands on `fn`
      // under the strict forward-barrier.
      {
        args: [TAtom, TAtom, TList],
        quoteArgs: new Set([0, 1]),
        patterns: new Map([[1, newAtom('fn')]]),
        noEvalArgs: new Set([2]),
        runInCheckMode: true,
        returns: [],
        handler: (args, _ctx, _stk, registry) => {
          const nameArg = args[0]!
          const name = nameArg.isWord() ? nameArg.asWord().name : nameArg.asAtom()
          if (/^-?\d/.test(name)) {
            throw new BoruError('syntax_error', `invalid numeric literal: ${name}`, name)
          }
          const elems = args[2]!.asList()
          if (elems.length === 0 || elems.length % 3 !== 0) {
            throw new BoruError('fn_invalid_spec', `fn: list length must be a non-zero multiple of 3`)
          }
          const sigs: FnSig[] = []
          for (let i = 0; i < elems.length; i += 3) {
            sigs.push(parseFnTriple(elems[i]!, elems[i + 1]!, elems[i + 2]!))
          }
          registry.check.recordDef(name)
          registry.pushDef(name, newFnDef({ sigs }))
          return []
        },
      },
      // Typed-name form `def x:Type value` — the jsonic parser emits
      // the annotation as a single-key implicit MAP {x: word(Type)}
      // (pair syntax), which this sig consumes. Mirrors the Go engspec
      // fixture's typedDef: exactly one key, the value must satisfy the
      // resolved constraint, a capitalised name refuses (the builtin
      // table owns type names — the L135 `def Integer 42` contract).
      {
        args: [TMap, TAny],
        noEvalArgs: new Set([0]),
        runInCheckMode: true,
        returns: [],
        handler: (args, _ctx, _stk, registry) => {
          const nameMap = args[0]!.asMap()
          if (nameMap.size !== 1) {
            throw new BoruError('type_error', 'def: typed-name map must have exactly one key', 'def')
          }
          const name = nameMap.keys()[0]!
          if (typeNameTable().has(name)) {
            throw new BoruError(
              'type_error',
              `type: name part ${JSON.stringify(name)} in ${JSON.stringify(name)} conflicts with an existing type name`,
              'def',
            )
          }
          let constraint = nameMap.get(name)!
          // Resolve a bare type-name Word constraint through the
          // cascade (defs, then the builtin table).
          if (constraint.isWord()) {
            const cn = constraint.asWord().name
            const bound = registry.topOfDefStack(cn)
            const bt = typeNameTable().get(cn)
            if (bound !== undefined) constraint = bound
            else if (bt !== undefined) constraint = newTypeLiteral(bt)
          }
          // The value slot resolves like every dispatched arg (Go's
          // typedDef receives the resolved value): `def x:null null`
          // must bind the atom, not the raw word.
          const value = resolveWordsDeep(args[1]!, registry)
          if (
            enforceTypeConstraint(
              registry,
              value,
              constraint,
              `def ${name}: value ${value.toString()} does not satisfy declared type ${constraint.toString()}`,
              name,
            )
          ) {
            return []
          }
          registry.check.recordDef(name)
          registry.pushDef(name, value)
          return []
        },
      },
      {
        // Name-binding form. The Atom quoteArgs slot captures the name
        // word (a constrained `NAME:[…]` word is kept intact so its
        // constraint survives — see the matcher's quoteArgs capture).
        // The value slot auto-evaluates like every plain arg (Go's
        // plainDef sig declares no NoEvalArgs): `def b [1 addq 2]`
        // binds the collected [3], and `def b [notaword]` errors at
        // def time, not at first reference.
        args: [TAtom, TAny],
        quoteArgs: new Set([0]),
        // Bind in check mode too, so later references resolve (otherwise
        // every `def x … x` cascades into undefined_word) — the binding is
        // a prerequisite for analysis, exactly as in Go. The bound carrier
        // carries the stripped-literal origin, so a compiled reference bakes
        // the value.
        runInCheckMode: true,
        returns: [],
        handler: (args, _ctx, _stk, registry) => {
          const nameArg = args[0]!
          const nameWord = nameArg.isWord() ? nameArg.asWord() : { name: nameArg.asAtom(), constraint: undefined }
          const name = nameWord.name
          const value = args[1]!
          // A builtin type name is not rebindable — post-opacity the
          // Word reaches def, which refuses with the same taxonomy the
          // Go InstallType path uses (resolution.tsv L135).
          if (typeNameTable().has(name)) {
            throw new BoruError(
              'type_error',
              `type: name part ${JSON.stringify(name)} in ${JSON.stringify(name)} conflicts with an existing type name`,
              'def',
            )
          }
          // A digit-first name is a malformed number, never a name.
          if (/^-?\d/.test(name)) {
            throw new BoruError('syntax_error', `invalid numeric literal: ${name}`, name)
          }
          // Colon-typed and container-typed names (`def x:5`,
          // `def l:[:Integer]`) always arrive as MAP tokens (the
          // tokenizer attaches the constraint as the map value), so
          // they dispatch to the typed-name map sig above — this
          // handler only ever sees plain names.
          // A capitalised name binding a class type stamps the struct
          // name onto it, so `inspect Name` reports struct:Name and a
          // child type can record `Class/Name` as its parent path.
          if (value.data instanceof ClassTypeInfo && value.data.name === '') {
            value.data.name = name
          }
          // Stage 2 (design/legacy/TYPE-REPRESENTATION.1.ignore §3, §9): a
          // CAPITALISED name mints a type node that denotes the binding and
          // carries the declared content — `def Color (enum […])` binds the
          // node Color, which renders as its name and `is Type`, while
          // membership, inspection and typeof read through to the content
          // (core typeContentOf). A bare type literal body is an ALIAS and
          // adopts that node, as Go's InstallType does (`def Pi Number` is
          // Number itself); a class value keeps its own payload (the stamp
          // above); a fn value is bound by the `def NAME fn` sig.
          let bound = value
          if (/^[A-Z]/.test(name) && !value.isTypeLiteral() && !value.isNone() && !(value.data instanceof ClassTypeInfo) && !value.isFnDef()) {
            // The content is the body with its type-name words resolved
            // (the parser is type-name-opaque: `[ :Integer ]` arrives with
            // word(Integer) as its child), as Go's install resolves it —
            // membership and inspection then read a finished shape. Under
            // the compile pass the body is a CARRIER whose literal the
            // recorder can usually recover (a stripped literal, a const
            // fold); the content is that value, so the compiled `2 is One`
            // is the interpreter's false and not a carrier's lenient yes.
            // A computed body the recorder cannot recover declines the
            // program: its node would carry no content the run can trust.
            let content = resolveWordsDeep(value, registry)
            if (content.carrier) {
              const emit = registry.check.emit as EmitState | undefined
              const concrete = emit === undefined ? null : emit.constValueOf(emit.classify(content))
              if (concrete !== null) {
                content = resolveWordsDeep(concrete, registry)
              } else if (emit !== undefined) {
                emit.markUncompilable(`def ${name}: a type name over a computed value (the node's content is the run's)`)
              }
            }
            bound = newTypeLiteral(mintNamedType(name, content))
          }
          registry.pushDef(name, bound)
          return []
        },
      },
    ],
  })

  // fn: builds a function-definition value from a single list of
  // triples `fn [ [params] [returns] [body] … ]`, mirroring the Go
  // `fn` fixture (ParseFnDef). The named-triple form (params is a list
  // of `name:Type` words) yields a callable FnDef; other forms (the
  // flat `fn [ Integer Integer [body] ]` and multi-sig shapes) produce
  // a Function value sufficient for typeof/is. fnsig builds a
  // FunctionSignature value.
  reg({
    name: 'fn',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // Build the fn value in check mode so def binds it and a later call
        // inlines the body (dispatchFnDefCheck/analyseFnBody), exactly as the
        // compiled-test fn fixture does.
        runInCheckMode: true,
        handler: (args) => {
          const elems = args[0]!.asList()
          if (elems.length === 0 || elems.length % 3 !== 0) {
            throw new BoruError('fn_invalid_spec', `fn: list length must be a non-zero multiple of 3`)
          }
          const sigs: FnSig[] = []
          for (let i = 0; i < elems.length; i += 3) {
            sigs.push(parseFnTriple(elems[i]!, elems[i + 1]!, elems[i + 2]!))
          }
          return [newFnDef({ sigs })]
        },
      },
    ],
  })
  reg({
    name: 'fnsig',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // Build the signature value in check mode so typeof/is consume it and
        // it bakes as an inert constant (its spec list is type literals).
        runInCheckMode: true,
        handler: (args, _ctx, _stk, registry) => {
          const elems = args[0]!.asList()
          if (elems.length === 0 || elems.length % 2 !== 0) {
            throw new BoruError('fnsig_invalid_spec', `fnsig: list length must be a non-zero multiple of 2`)
          }
          // Resolve bare type-name Words in the spec lists (post-
          // opacity, `[ Integer ]` arrives as [word(Integer)]).
          return [newFnUndef(elems.map((e) => resolveWordsDeep(e, registry)))]
        },
      },
    ],
  })

  // quote: capture the next forward token as data.
  //   sig [Atom] quoteArgs: captures the upcoming Word as an Atom name
  //                (so `quote dup` yields dup/q).
  //   sig [TAny]:  catch-all passthrough (`quote 5` → 5,
  //                `quote [1 2]` → (quote [1 2])).
  reg({
    name: 'quote',
    forwardPrecedence: true,
    // The TAny slot needs noEvalArgs so a List arg arrives raw
    // rather than auto-evaluating before the handler sees it.
    signatures: [
      {
        args: [TAtom],
        quoteArgs: new Set([0]),
        // quote returns the captured NAME verbatim (never resolves it), so
        // [quote <word>] re-runs faithfully as a self-contained island.
        recordsOwnEvent: true,
        returnsFn: (args, registry) => {
          const out = newDynamicCarrier(TAtom)
          const emit = registry.check.emit as EmitState | undefined
          if (emit !== undefined) {
            const a = args[0]!
            const name = a.isWord() ? a.asWord().name : a.data !== null ? a.asAtom() : ''
            if (name !== '') {
              emit.recordTokenIsland([newWord('quote'), newWord(name)], out, 'quote')
            } else {
              // A non-name operand (e.g. `quote null`): bake the value itself
              // — quote returns it verbatim.
              const op = emit.classify(a)
              const tok = a.isConcrete() ? a : op !== null && op.kind === 'const' ? op.value : null
              if (tok !== null) emit.recordTokenIsland([newWord('quote'), tok], out, 'quote')
              else emit.markUncompilable('quote: non-bakeable operand')
            }
          }
          return [out]
        },
        handler: (args) => [args[0]!],
      },
      {
        args: [TAny],
        noEvalArgs: new Set([0]),
        // quote returns its arg RAW (never evaluated), so re-running
        // [quote <value>] reproduces it — island it. Only an inert value is
        // bakeable as a token; a non-inert arg (code/carrier) falls back.
        recordsOwnEvent: true,
        returnsFn: (args, registry) => {
          const out = newDynamicCarrier(TAny)
          const emit = registry.check.emit as EmitState | undefined
          const a = args[0]!
          if (emit !== undefined) {
            // A raw value (eval-list/map) bakes verbatim (quote returns it
            // unevaluated); a stripped literal / type operand bakes via its
            // classified const original (quote 5, quote Integer).
            let tok: import('@boru-lang/core').Value | null = a.isConcrete() ? a : null
            if (tok === null) {
              const op = emit.classify(a)
              if (op !== null && op.kind === 'const') tok = op.value
            }
            if (tok !== null) emit.recordTokenIsland([newWord('quote'), tok], out, 'quote')
            else emit.markUncompilable('quote: non-bakeable value operand')
          }
          return [out]
        },
        handler: (args) => {
          const v = args[0]!
          if (v.vType.matches(TList) && v.isConcrete()) {
            return [withQuoted(v)]
          }
          return [v]
        },
      },
    ],
  })

  // end is a pure boundary keyword handled by Engine.run; registering
  // it as a 0-arg fallback isn't required, but we also don't register
  // it as a normal native — the engine intercepts the Word at the
  // pointer and removes / fires accordingly (see Engine.stepEnd).

  // args: 0-arg word that returns the current fn-call's argument
  // frame as a list. dispatchFnDef pushes the matched args (in sig
  // order) before running the body so bodies can reference
  // positional args by index without naming each param. Empty list
  // when there's no active fn call.
  reg({
    name: 'args',
    forwardPrecedence: false,
    signatures: [
      {
        args: [],
        // `args` reads the current call's positional-arg frame. Inside an
        // inlined fn body that frame holds the param operands (analyseFnBody
        // pushes it), so record a makeList of them — the VM rebuilds the list
        // with no runtime frame. Outside a frame (or with an unresolvable
        // operand) it refuses. recordsOwnEvent so the makeList is the event.
        recordsOwnEvent: true,
        returnsFn: (_a, r) => {
          const emit = r.check.emit
          const frame = r.topArgs()
          if (emit !== undefined) {
            if (frame === undefined) {
              // No call frame (top level): args is the empty list.
              return [emit.recordMakeList([])]
            } else {
              const ops = frame.map((v) => emit.classify(v))
              if (ops.every((o) => o !== null)) return [emit.recordMakeList(ops as import('./emit.ts').Operand[])]
              emit.markUncompilable('args: frame operand of unknown provenance')
            }
          }
          return [newDynamicCarrier(TList)]
        },
        handler: (_args, _ctx, _stk, registry) => {
          const top = registry.topArgs()
          return [newList(top ? [...top] : [], { eval: false })]
        },
      },
    ],
  })

  // break / continue — outside a loop they bubble out as an error,
  // mirroring registerEngSpecDefinition's flow-ctrl stubs.
  reg({
    name: 'break',
    signatures: [
      {
        args: [],
        handler: () => {
          throw new BoruError('flow_error', 'break outside loop')
        },
      },
    ],
  })
  reg({
    name: 'continue',
    signatures: [
      {
        args: [],
        handler: () => {
          throw new BoruError('flow_error', 'continue outside loop')
        },
      },
    ],
  })

  // undef NAME — pop the named binding. A capitalised (type) name with
  // no binding is a type_error; a lowercase unbound name is a harmless
  // no-op. Mirrors registerEngSpecDefinition::undef.
  reg({
    name: 'undef',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TWord],
        // Mutates the def stack — a compile-time effect like def, so run it in
        // check mode (returns nothing) and a later reference resolves correctly.
        runInCheckMode: true,
        returns: [],
        handler: (args, _ctx, _stk, registry) => {
          const name = args[0]!.asWord().name
          const has = registry.topOfDefStack(name) !== undefined
          if (/^[A-Z]/.test(name) && !has) {
            throw new BoruError('type_error', `undef ${name}: no such type binding`, name)
          }
          if (has) registry.popDef(name)
          return []
        },
      },
    ],
  })

  // replay: takes a body list, emits Mark + body + Move so the body
  // executes once, then the Move replays it — net effect: body runs
  // twice. Demonstrates the mark/move plumbing without pulling in
  // for/while continuation semantics.
  reg({
    name: 'replay',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        handler: (args) => {
          const body = args[0]!.asList()
          replayCounter++
          const id = `__replay_${replayCounter}`
          return [newMark(id, [...body]), ...body, newMove(id)]
        },
      },
    ],
  })

  // typeof / pathof / is — type-introspection fixtures, mirroring
  // test/go/engspec/engspec_test.go::registerEngSpecTypeWords. They
  // delegate to the ported algorithm primitives in coretype.ts.
  reg({
    name: 'typeof',
    forwardPrecedence: true,
    signatures: [{ args: [TAny], handler: (args) => [typeOf(args[0]!)] }],
  })
  reg({
    name: 'pathof',
    forwardPrecedence: true,
    signatures: [{ args: [TAny], typeArgs: new Set([0]), handler: (args) => [pathOf(args[0]!)] }],
  })
  // tor — union (disjunct) of two type values. enum — a fixed
  // enumeration. tand — type intersection (only its sig is inspected
  // by the corpus, so a minimal handler suffices). Mirror
  // registerEngSpecTypeOps + registerEngSpecTypeWords::enum.
  const flattenAlts = (v: Value): Value[] => (v.isDisjunct() ? v.asDisjunct().alternatives : [v])
  // compareAlt mirrors eng/go CompareValues for the value shapes a union
  // alternative can take (type literals + scalar concretes): a per-family
  // "type-literal sorts before a concrete inhabitant" rule, cross-leaf numeric
  // magnitude for concrete numbers, then lattice rank. Returns 0 to defer to a
  // canon tiebreak (magnitude-equal cross-leaf pairs, same-rank literals).
  const familyRoot = (v: Value): BoruType | null => {
    for (const root of [TNumber, TString, TBoolean, TAtom]) {
      if (v.vType.matches(root)) return root
    }
    return null
  }
  const compareAlt = (a: Value, b: Value): number => {
    const fa = familyRoot(a)
    const fb = familyRoot(b)
    if (fa !== null && fb !== null && fa.equal(fb)) {
      const aLit = a.data === null
      const bLit = b.data === null
      if (aLit !== bLit) return aLit ? -1 : 1 // litVsConcreteOrder: literal first
      if (!aLit && !bLit && fa.equal(TNumber)) {
        // Project both leaves to a JS number (Integer data is a bigint) so the
        // magnitude comparison is cross-leaf, like Go's Number Comparer.
        const num = (v: Value): number =>
          v.vType.matches(TInteger) ? Number(v.asInteger()) : v.asFloat()
        const na = num(a)
        const nb = num(b)
        if (na < nb) return -1
        if (na > nb) return 1
        return 0 // magnitude-equal (1 vs 1.0) → canon tiebreak
      }
    }
    const ra = builtinRank(a.vType)
    const rb = builtinRank(b.vType)
    return ra !== rb ? ra - rb : 0
  }
  reg({
    name: 'tor',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny, TAny],
        barrierPos: 1,
        // Build the disjunct in check mode (like `refine`) so a consumer —
        // `inspect` of a def bound to `A tor B` — sees the concrete type and
        // bakes it as an inert const rather than refusing a dynamic carrier.
        runInCheckMode: true,
        handler: (args, _ctx, _stk, registry) => {
          // A stripped concrete operand (a check-mode carrier): the
          // runtime disjunct (`2.0 tor 100`) differs from the carrier
          // one (`Integer tor Float`), so baking the check-shape is a
          // miscompile — return a dynamic carrier and let the program
          // fall back to the interpreter. Type-literal operands (the
          // `def T (A tor B)` inspect rows) stay concrete and bake.
          if (registry.check.isActive() && (args[0]!.carrier || args[1]!.carrier)) {
            return [newDynamicCarrier(TDisjunct)]
          }
          const alts = [...flattenAlts(args[1]!), ...flattenAlts(args[0]!)]
          const seen = new Set<string>()
          const out: Value[] = []
          for (const a of alts) {
            const k = canon([a])
            if (!seen.has(k)) {
              seen.add(k)
              out.push(a)
            }
          }
          // `tor` is commutative: store the alternatives in canonical
          // (tcmp-equivalent) order so `A tor B` and `B tor A` reduce to the
          // identical value — mirrors eng/go SimplifyDisjunctAlts →
          // disjunctAltLess → CompareValues, keeping the cross-engine
          // differential in agreement with the Go kernel. The primary key is
          // the value order (NOT builtinRank alone): within a family a bare
          // type literal sorts before a concrete inhabitant, and concrete
          // numbers sort by numeric magnitude across Integer/Float — so
          // `Integer tor 0` and `100 tor 2.0` match the Go kernel's order. A
          // canon tiebreak settles ties (cross-leaf magnitude-equality like
          // `1 tor 1.0`, and same-rank literals/atoms).
          out.sort((a, b) => {
            const c = compareAlt(a, b)
            if (c !== 0) return c
            const ka = canon([a])
            const kb = canon([b])
            return ka < kb ? -1 : ka > kb ? 1 : 0
          })
          if (out.length === 1) return [out[0]!]
          return [newDisjunct(out)]
        },
      },
    ],
  })
  reg({
    name: 'tand',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TAny, TAny],
        barrierPos: 1,
        handler: (args) =>
          canon([args[0]!]) === canon([args[1]!]) ? [args[0]!] : [newTypeLiteral(TNever)],
      },
    ],
  })
  reg({
    name: 'enum',
    forwardPrecedence: true,
    signatures: [
      {
        args: [TList],
        noEvalArgs: new Set([0]),
        // Build the enum type value in check mode so typeof/is consume it and
        // it bakes (its alternatives are atoms/inert literals).
        runInCheckMode: true,
        handler: (args, _ctx, _stk, registry) => {
          // A typed list `[:T …]` carries a child constraint each
          // element must satisfy; a plain list has none.
          const list = args[0]!
          const hasChild = list.isTypedList()
          // Resolve a bare type-name Word child (`[:Integer …]` post-
          // opacity) through the cascade so validation and the error
          // message see the type, not the word.
          const child = hasChild ? resolveWordsDeep(list.asChildType().child, registry) : undefined
          const elems = hasChild ? list.asChildType().elements : list.asList()
          const alts = elems.map((e) => {
            const v = e.isWord() ? newAtom(e.asWord().name) : e
            // Validate each element against the child constraint: interpret
            // mode throws, compile mode traps/refuses, pure check mode is
            // lenient (see enforceTypeConstraint). The trap is terminal, so a
            // still-being-built enum past it is never observed at run time.
            if (child !== undefined) {
              enforceTypeConstraint(
                registry,
                v,
                child,
                `enum: element ${v.toString()} does not satisfy ${child.vType.leaf()}`,
                'enum',
              )
            }
            return v
          })
          return [newEnum(alts)]
        },
      },
    ],
  })
  reg({
    name: 'is',
    signatures: [
      {
        args: [TAny, TAny],
        barrierPos: 1,
        // The constraint side resolves bare type-name Words through the
        // cascade (post-opacity, `[:Integer]` carries word(Integer)).
        handler: (args, _ctx, _stk, registry) => [
          newBoolean(isValueOfType(resolveWordsDeep(args[1]!, registry), resolveWordsDeep(args[0]!, registry))),
        ],
      },
    ],
  })

  // Simple-value defs the def.tsv spec references. A word whose name
  // is in the def stack is substituted by its value before normal
  // dispatch, provided the value isn't an FnDef / ClassType.
  r.pushDef('pi', newInteger(3n))
  r.pushDef('tau', newInteger(6n))
  r.pushDef('greeting', newString('hello'))
}

// ── Tokenizer ─────────────────────────────────────────────────────────────


function tokenize(s: string): Value[] {
  // The jsonic-based parser (src/parser) is the single parsing path —
  // stream-verified against the Go parser's oracle (0 divergences over
  // the eng/spec corpus). The legacy hand-rolled tokenizer below
  // (legacyTokenize/readTokens) is retained only as a comparison
  // oracle during the transition and is no longer called by the
  // fixtures.
  return parse(s)
}



// parseFnTriple parses one [params][returns][body] triple into an
// FnSig. The named form has a params list (`[n:Integer ?]`); the flat
// form has bare type literals for the param/return slots.
function parseFnTriple(p: Value, r: Value, b: Value): FnSig {
  let params: FnParam[] = []
  if (p.vType.matches(TList) && Array.isArray(p.data)) {
    for (const pe of p.asList()) {
      if (pe.isWord() && pe.asWord().name === '?') {
        if (params.length > 0) params[params.length - 1]!.optional = true
        continue
      }
      params.push(parseFnParam(pe))
    }
  } else {
    // Flat form: the param slot is a bare type (unnamed param).
    params = [{ name: '', type: parseFnReturn(p) }]
  }
  const returns =
    r.vType.matches(TList) && Array.isArray(r.data)
      ? r.asList().map((x) => parseFnReturn(x))
      : [parseFnReturn(r)]
  const body = b.vType.matches(TList) && Array.isArray(b.data) ? b.asList() : [b]
  return { params, returns, body }
}

/**
 * Parse one fn-param token. The spec tokenizer produces a Word per
 * whitespace-split chunk, so a typed param like `n:Integer` arrives
 * as a single Word with name `n:Integer`. Split on the first `:`,
 * resolve the type name, build an FnParam.
 */
function parseFnParam(v: Value): FnParam {
  // The jsonic parser converts `n:Integer` inside a param list to an
  // implicit single-entry MAP {n: word(Integer)} (pair syntax in data
  // context) — the named-param form ParseFnParams keys on in Go. The
  // legacy fixture tokenizer produced a Word 'n:Integer'; both shapes
  // are accepted here.
  if (v.isMap() && v.data instanceof OrderedMap && v.asMap().size === 1) {
    const m = v.asMap()
    const name = m.keys()[0]!
    const tv = m.get(name)!
    const typeName = tv.isWord() ? tv.asWord().name : tv.data === null ? tv.vType.leaf() : ''
    const type = typeNameTable().get(typeName)
    if (!type) throw new Error(`fn: unknown type ${JSON.stringify(typeName)}`)
    return { name, type }
  }
  if (!v.isWord()) {
    throw new Error(`fn: expected param Word, got ${v.toString()}`)
  }
  const w = v.asWord()
  const idx = w.name.indexOf(':')
  if (idx < 0) {
    throw new Error(`fn: param ${JSON.stringify(w.name)} missing ':TypeName' suffix`)
  }
  const name = w.name.slice(0, idx)
  const typeName = w.name.slice(idx + 1)
  const type = typeNameTable().get(typeName)
  if (!type) throw new Error(`fn: unknown type ${JSON.stringify(typeName)}`)
  return { name, type }
}

/** Parse one fn-return token (a bare TypeName Word). */
function parseFnReturn(v: Value) {
  // A return slot is a type — either a resolved type literal (the
  // tokenizer turns bare `Integer` into one) or a bare TypeName word.
  if (v.data === null) return v.vType
  if (!v.isWord()) throw new Error(`fn: expected return type`)
  const w = v.asWord()
  const type = typeNameTable().get(w.name)
  if (!type) throw new Error(`fn: unknown return type ${JSON.stringify(w.name)}`)
  return type
}

// unsupportedMake is the placeholder handler for make/get/set/refine
// overloads whose construction isn't ported yet; their signatures still
// drive inspect rendering.
function unsupportedMake(what: string): Value[] {
  throw new BoruError('unsupported', `make/${what}: not yet ported`)
}

// buildWordInspection renders a registered word's metadata as an
// inspection map: {name:'…' kind:native signatures:[{args:['…' …]} …]}.
function buildWordInspection(
  name: string,
  fn: { declOrder: { args: { leaf(): string }[] }[] },
): Value {
  const om = new OrderedMap()
  om.set('name', newString(name))
  om.set('kind', newWord('native'))
  const sigs = fn.declOrder.map((sig) => {
    const sm = new OrderedMap()
    sm.set('args', newList(sig.args.map((t) => newString(t.leaf())), { eval: false }))
    return newMap(sm)
  })
  om.set('signatures', newList(sigs, { eval: false }))
  return newInspect(om)
}

// buildTypeInspection renders a value's type structure as an inspection
// map, mirroring buildTypeInspection in eng/go. Kinds: literal (bare
// type / concrete value), record, typed_list, typed_map, disjunct,
// function_shape, unknown (atom name lookup).
function strList(items: string[]): Value {
  return newList(items.map((s) => newString(s)), { eval: false })
}
// buildClassType assembles a class-type value from a parent path,
// the parent's inherited fields, and a field map. Inherited fields keep
// their order and are followed by the map's own fields.
function buildClassType(parentPath: string, inherited: OrderedMap, fieldMap: Value): Value {
  const fields = new OrderedMap()
  for (const k of inherited.keys()) fields.set(k, inherited.get(k)!)
  const m = fieldMap.asMap()
  for (const k of m.keys()) fields.set(k, m.get(k)!)
  return newClassType(new ClassTypeInfo('', parentPath, fields))
}

function buildTypeInspection(v: Value): Value {
  const om = new OrderedMap()
  // A concrete atom is treated as a name to look up.
  if (v.vType.equal(TAtom) && v.data !== null) {
    om.set('name', newString(v.asAtom()))
    om.set('kind', newWord('unknown'))
    om.set('signatures', newList([], { eval: false }))
    return newInspect(om)
  }
  // Typed list / typed map.
  if (v.isTypedList() || v.isTypedMap()) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.isTypedMap() ? 'Map' : 'List'))
    om.set('kind', newWord(v.isTypedMap() ? 'typed_map' : 'typed_list'))
    om.set('child', newString(v.asChildType().child.vType.toString()))
    return newInspect(om)
  }
  // Disjunct / Enum.
  if (v.isDisjunct()) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.vType.leaf()))
    om.set('kind', newWord('disjunct'))
    om.set('alternatives', strList(v.asDisjunct().alternatives.map((a) => a.vType.toString())))
    return newInspect(om)
  }
  // FunctionSignature (fnsig) — pairs of [params][returns]. The bare
  // type literal renders as function_shape with no signatures.
  if (v.vType.equal(typeTable.get('FunctionSignature')!)) {
    om.set('type', newString('Type'))
    om.set('struct', newString('FunctionSignature'))
    om.set('kind', newWord('function_shape'))
    const pairs = Array.isArray(v.data) ? (v.data as Value[]) : []
    const sigs: Value[] = []
    for (let i = 0; i + 1 < pairs.length; i += 2) {
      const sm = new OrderedMap()
      sm.set('params', strList(pairs[i]!.asList().map((p) => p.vType.leaf())))
      sm.set('returns', strList(pairs[i + 1]!.asList().map((r) => r.vType.leaf())))
      sigs.push(newMap(sm))
    }
    om.set('signatures', newList(sigs, { eval: false }))
    return newInspect(om)
  }
  // Class type (class {…}): kind:object with its struct name,
  // optional parent path (omitted for a direct child of the base
  // Class), and its fields rendered as a name→type-leaf map.
  if (v.data instanceof ClassTypeInfo) {
    const info = v.data
    om.set('type', newString('Type'))
    om.set('struct', newString(info.name))
    om.set('kind', newWord('object'))
    if (info.parentPath !== 'Class') om.set('parent', newString(info.parentPath))
    const fields = new OrderedMap()
    for (const k of info.fields.keys()) fields.set(k, newString(info.fields.get(k)!.vType.leaf()))
    om.set('fields', newMap(fields))
    return newInspect(om)
  }
  // Bare type literals (incl. the none value) and concrete values.
  if (v.isNone()) {
    om.set('type', newString('None'))
    om.set('kind', newWord('literal'))
    return newInspect(om)
  }
  if (v.data === null) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.vType.leaf()))
    om.set('kind', newWord('literal'))
    return newInspect(om)
  }
  // Any other type body whose VType lives under Type (e.g. a Function
  // value) is a TYPE literal of its leaf.
  if (v.vType.matches(TType)) {
    om.set('type', newString('Type'))
    om.set('struct', newString(v.vType.leaf()))
    om.set('kind', newWord('literal'))
    return newInspect(om)
  }
  // Record-shape map → a TYPE.
  if (isRecordShape(v)) {
    om.set('type', newString('Type'))
    om.set('struct', newString('Map'))
    om.set('kind', newWord('record'))
    const fields = new OrderedMap()
    const m = v.asMap()
    for (const k of m.keys()) fields.set(k, newString(m.get(k)!.vType.leaf()))
    om.set('fields', newMap(fields))
    return newInspect(om)
  }
  // Any other concrete value — a literal of its own type.
  om.set('type', newString(v.vType.leaf()))
  om.set('kind', newWord('literal'))
  return newInspect(om)
}

// buildDefinedInspection renders a def-bound name: a bound type body
// gets the type inspection prefixed with name; an FnDef gets kind:
// defined with its param signatures plus a synthetic 0-arg fallback;
// a plain value gets kind:defined with its rendered value.
function buildDefinedInspection(name: string, top: Value): Value {
  if (!top.isFnDef() && (top.data === null || isTypeBody(top))) {
    const insp = buildTypeInspection(top).asMap()
    const om = new OrderedMap()
    om.set('name', newString(name))
    for (const k of insp.keys()) om.set(k, insp.get(k)!)
    return newInspect(om)
  }
  const om = new OrderedMap()
  om.set('name', newString(name))
  om.set('kind', newWord('defined'))
  if (top.isFnDef()) {
    const fd = top.asFnDef()
    const sigMaps = fd.sigs.map((s) => {
      const sm = new OrderedMap()
      sm.set('args', newList(s.params.map((p) => newString(p.type.leaf())), { eval: false }))
      return newMap(sm)
    })
    const empty = new OrderedMap()
    empty.set('args', newList([], { eval: false }))
    sigMaps.push(newMap(empty))
    om.set('signatures', newList(sigMaps, { eval: false }))
  } else {
    om.set('value', top)
    om.set('signatures', newList([], { eval: false }))
  }
  return newInspect(om)
}

// renderStack renders the residual stack as canonical boru source via
// the ported Canon, matching the Go engspec runner's eng.Canon output.
function renderStack(stack: Value[]): string {
  return canon(stack)
}

// ── Test harness ─────────────────────────────────────────────────────────

interface SpecRow {
  lineNum: number
  input: string
  expected: string
}

function parseSpec(file: string): SpecRow[] {
  const text = fs.readFileSync(file, 'utf8')
  const rows: SpecRow[] = []
  text.split('\n').forEach((raw, idx) => {
    const lineNum = idx + 1
    const trimmed = raw.replace(/[ \t]+$/, '')
    if (trimmed === '' || trimmed.startsWith('#')) return
    const parts = trimmed.split('\t')
    if (parts.length < 2) {
      throw new Error(`${file}:L${lineNum}: malformed row, want at least input<TAB>expected`)
    }
    rows.push({
      lineNum,
      input: parts[0]!.trim(),
      expected: parts[1]!.trim(),
    })
  })
  return rows
}

export { SPEC_DIR, registerSpecWords, tokenize, renderStack, parseSpec }
export type { SpecRow }

