// Command genhelp pre-computes help example results by running each
// expression through the boru native. Output is written to
// lang/go/engine/help/examples_gen.go as a static map.
//
//go:generate go run .
package main

import (
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/boru-lang/boru/lang/go/capabilities"
	"github.com/boru-lang/boru/lang/go/native"
	"github.com/boru-lang/boru/lang/go/native/help"
	"github.com/boru-lang/boru/parser/go"
)

// outputPath returns the absolute path of the generated file, derived from
// this source file's location so it works regardless of the working
// directory: <repo>/cmd/go/genhelp/main.go -> <repo>/lang/go/native/help/examples_gen.go
func outputPath() string {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	return filepath.Join(repoRoot, "lang", "go", "native", "help", "examples_gen.go")
}

// osExit is a test seam (design/TEST-SEAMS.10.md); tests swap it to
// observe exit codes without killing the process.
var osExit = os.Exit

// runGenhelp is a test seam (design/TEST-SEAMS.10.md); tests swap it so
// main() is drivable without regenerating the committed examples file.
var runGenhelp = run

// newDefaultRegistry is a test seam (design/TEST-SEAMS.10.md); tests
// swap it to drive run's registry-construction and seed-fs error arms.
var newDefaultRegistry = native.DefaultRegistry

// exampleExprs is a test seam (design/TEST-SEAMS.10.md); tests swap it
// to drive the duplicate-expression skip, which the real example corpus
// never reaches.
var exampleExprs = help.ExampleExprs

// formatSource is a test seam (design/TEST-SEAMS.10.md); tests swap it
// to drive the gofmt-failure arm; renderSource always emits well-formed
// source, so the arm is otherwise unreachable.
var formatSource = format.Source

func main() {
	if err := runGenhelp(outputPath(), os.Stderr); err != nil {
		fmt.Fprintf(os.Stderr, "genhelp: %v\n", err)
		osExit(1)
	}
}

// run computes every word's example results and writes the generated
// source to outPath. Extracted from main so tests can drive the exact
// production pipeline against a temp path.
func run(outPath string, errw io.Writer) error {
	reg, err := newDefaultRegistry()
	if err != nil {
		return err
	}
	reg.SetParseFunc(parser.Parse)

	// Collect all example expressions across all words.
	// Use a fresh registry per word to avoid state leakage between examples.
	results := map[string]string{}
	words := help.Words()
	sort.Strings(words)

	for _, word := range words {
		info := native.BuildFuncInfo(reg, word)
		if info == nil {
			continue
		}
		exprs := exampleExprs(*info)

		// Fresh registry per word.
		wordReg, err := newDefaultRegistry()
		if err != nil {
			return err
		}
		wordReg.SetParseFunc(parser.Parse)
		if err := seedMemFS(wordReg); err != nil {
			return fmt.Errorf("seed fs: %w", err)
		}

		for _, expr := range exprs {
			if _, done := results[expr]; done {
				continue
			}
			// One encoding for both paths (help.EncodeExampleResult):
			// a compile failure renders `error [boru/<code>]`, an empty stack
			// renders `(no value)`, and anything not documentable —
			// an uncoded failure, `undefined_word` from this
			// import-less registry, or a run-specific identity — is
			// left out. See design/ROC-ADOPTION-PLAN.0.md (A4).
			encoded, ok := help.EncodeExampleResult(evalExpr(wordReg, expr))
			if !ok {
				continue
			}
			results[expr] = encoded
		}
	}

	src, err := formatSource([]byte(renderSource(results)))
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	if err := os.WriteFile(outPath, src, 0644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Fprintf(errw, "genhelp: wrote %d examples to %s\n", len(results), outPath)
	return nil
}

// renderSource renders the results map as the generated Go source file,
// with keys sorted for deterministic output.
func renderSource(results map[string]string) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/go/genhelp; DO NOT EDIT.\n\n")
	b.WriteString("package help\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\texampleResults = map[string]string{\n")

	keys := make([]string, 0, len(results))
	for k := range results {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		b.WriteString(fmt.Sprintf("\t\t%q: %q,\n", k, results[k]))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

// seedMemFS installs an in-memory filesystem on reg seeded with the
// same files the help-example validation test expects (see
// lang/go/test/help_examples_test.go), so precomputed read/write
// example results match what the test reproduces.
func seedMemFS(reg *native.Registry) error {
	mem := capabilities.NewMem()
	for _, name := range []string{"a", "b", "c", "d", "e"} {
		mem.Files[name] = []byte("file-" + name + "-content")
	}
	if err := reg.Capabilities.Set(native.CapMemFileOps, capabilities.FileOps(mem)); err != nil {
		return err
	}
	// Enable the in-memory filesystem: __sys.fs.mem = true in the root
	// context, matching enableMemFS in the validation test.
	prog := []native.Value{
		native.NewWord("context"), native.NewWord("dot"), native.NewWord("__sys"),
		native.NewWord("dot"), native.NewWord("fs"),
		native.NewWord("set"), native.NewWord("mem"), native.NewBoolean(true),
	}
	eng := native.New(reg)
	_, err := eng.Run(prog)
	return err
}

func evalExpr(reg *native.Registry, expr string) (string, error) {
	vals, err := parser.Parse(expr)
	if err != nil {
		return "", err
	}

	// Suppress output from print/trace.
	savedOut := reg.Output
	reg.Output = io.Discard
	defer func() { reg.Output = savedOut }()

	eng := native.NewTop(reg)
	result, err := eng.Run(vals)
	if err != nil {
		return "", err
	}
	var parts []string
	for _, v := range result {
		parts = append(parts, v.String())
	}
	return strings.Join(parts, " "), nil
}
