# TS-PARITY-AUDIT.0 — parser battery parity audit

**Status:** COMPLETE; every corpus row agrees in both ports. Open-input
probing (2026-08-09) found divergences beyond the corpus; the live ledger
`parser/spec/divergent.tsv` carries one measured row per class — see
parser/spec/README.md §"The current debt" · **Started:** 2026-08-07
(maintainer instruction: "Bring ts up to 100% and carve out the ts parser
module. Report on parity and coverage when done")

`parser/ts/src/parse-battery.test.ts` opens by declaring "The Go parser is
the REFERENCE: every construct converts to the same value stream" and "The
Go parser is the reference for every render here." Both claims were checked
mechanically for the first time by this audit. **Of 257 checkable rows, 15
encode a render parser/go does not produce.** The battery was pinning TS's
own behaviour, so the twins could drift without any gate noticing.

## The oracle

The battery renders `canon(parse(src))`, or `'ERR ' + first line` on throw.
The Go equivalent is `CanonValue` over each value, space-joined. A temporary
test in `parser/go` reproduces it exactly:

```go
func renderOracle(src string) string {
	vals, err := parser.Parse(src)
	if err != nil {
		return "ERR " + strings.SplitN(err.Error(), "\n", 2)[0]
	}
	parts := make([]string, 0, len(vals))
	for _, v := range vals {
		parts = append(parts, core.CanonValue(v))
	}
	return strings.Join(parts, " ")
}
```

Drive it with the battery's own sources (extract them by `eval`-ing the
`rows` array in node) and diff against the recorded expectations. Two
apparent diffs are extraction artifacts — rows whose source contains a real
newline — and are excluded from the 15 below.

## The original 15 divergences

**Big-decimal canon keeps its `0d` prefix in Go, drops it in TS.** Six rows:

| source | battery expects | parser/go renders |
|---|---|---|
| `0d123` | `123` | `0d123` |
| `0D45_6` | `456` | `0d456` |
| `-0d789` | `-789` | `-0d789` |
| `0d1_2.3` | `12.3` | `0d12.3` |
| `0d1e2` | `100` | `0d100` |
| `0d1.5e2` | `150` | `0d150` |
| `0d1_2e1_0` | `120000000000` | `0d120000000000` |

`0d99999999999999999999` diverges the same way. This is a **canon**
divergence — `core/ts`'s `canonValue` against `core/go`'s `CanonValue` — not
a parser one, so it is mis-filed in the parser battery.

**Marker values render as text in TS, as empty in Go.** `1 ;` → battery
expects `1 end`, Go renders `1 ` (the End value canons to the empty string).
Same shape for a stray close paren: `1 )` → TS `1 )`, Go `1 `.

**Typed containers keep their tag in TS, drop it in Go.** `[:Integer]` →
TS `[:word(Integer)]`, Go `[]`. `[:Integer 1 2]` → TS `[:word(Integer) 1 2]`,
Go `[1 2]`. `[:Box<Integer>]` → TS `[:sugar(angle Box [word(Integer)])]`,
Go `[]`. And in the other direction `{:Integer k:1}` → TS `{:word(Integer)}`
(the entry is DROPPED), Go `{k:1}` (the tag is dropped). That last one is
not a rendering difference — the two parsers keep different data.

**Error text differs.** `1_` → TS `invalid numeric literal: 1_`, Go
`` misplaced `_` in numeric literal: 1_ ``.

**Float overflow is not an error in TS.** `1e400` → TS returns `inf`, Go
raises `[boru/float_overflow]: floating-point literal out of range`.
`-1e400` likewise. This is the most substantive of the fifteen: the engines
disagree about whether a program is *valid*, not about how to print it.

Three further divergences were found by rows added in this change and are
not in the table above because they were removed rather than landed:
`{:Integer k:1}`, `[: ]` (Go `[]`, TS raises "empty list element"), and
`1 )`.

## Why the gates missed it

Nothing cross-checks the two parsers on the same input. `make crossdiff`
runs the **engine** twins over `eng/spec` and hard-fails only when both
produce a value and the values differ, so a parser-level render difference
that still evaluates alike never surfaces. The battery is the only
parser-level breadth suite and it is TS-only.

## Recommendation

Move the battery's rows into a shared TSV corpus under `parser/spec/`, read
by both `parser/go` and `parser/ts` the way `core/spec` is read by
`core/go/corespec_test.go` and `core/ts/src/corespec.test.ts` — two runners,
no shared scaffolding, one corpus. Then a divergence is a red suite rather
than a silent drift. Until that lands, treat the battery's expectations as
unverified: 57 rows added in this change ARE Go-verified (they were
generated by the oracle above), and the pre-existing 257 are not, apart from
the 240 this audit confirms agree.

## Update — the stream oracle, finally run

`make parser-crossdiff` now runs both dumpers over `eng/spec` and diffs them.
The later `parser-parity` CI gate runs it alongside both standalone 100%
coverage suites. Wiring up the oracle that had shipped unused immediately found
**three real defects in `core/ts`'s `Value.toString()`**, none of them visible
to any existing gate:

1. **`[object Object]`.** There was no disjunction arm at all, so every union
   in a parsed stream fell through to `String(this.data)` on a `DisjunctInfo`.
   Go joins the alternatives with `" tor "` (`core/go/value.go:3660`).
2. **The `None` type literal rendered as the `none` value.** A `TNone` special
   case fired for both, so the None *alternative* of a union printed `none`.
   Only the none VALUE is lowercase; `canonValue` already drew that line.
3. **Type literals rendered by full path.** `newTypeLiteral(TInteger)` printed
   `Scalar/Number/Integer`; Go prints `Integer`, and `canonValue` already used
   `leaf()`. An `eng/ts` test had pinned the wrong value
   (`value-arms.test.ts:148`), which is what kept it alive.

After the fixes the differential is **0 divergences across 1,765 rows**.

The three sat in a genuine blind spot. `crossdiff` compares the two ENGINES
and hard-fails only when both produce a value and the values differ, so a
render difference that still evaluates alike is invisible to it; `parser/spec`
is a curated contract and did not enumerate these shapes; and defect 3 was
actively protected by a test asserting it.

The original 15 `divergent.tsv` rows were subsequently adjudicated and the
ledger is now empty. Later measurement found and closed depth, rule-step, and
numeric-token-boundary gaps too. `parse.tsv`, generated `nesting.tsv`, and the
structural `shape.tsv` now exercise distinct parser contracts with independent
Go and TypeScript readers/renderers; `parser-crossdiff` remains the broad
1,765-row sweep.
