// The generated compiled-coverage status surface.
//
// TestCompiledStatus renders the live census (gatherCensus) into a committed
// Markdown document, COMPILED_STATUS.md, and fails if the committed copy is
// stale. It is the single readable answer to "how much of the language
// compiles, and what is left" — derived from the corpus on every run, so it
// cannot drift the way a hand-maintained number does.
//
// Refresh after any change that moves coverage:
//
//	make status
//	# or: BORU_WRITE_STATUS=1 go test ./langspec/ -run TestCompiledStatus
//
// The numbers come from exactly the same walk the ceiling gates use, so a
// refreshed status and a green TestCompiledCoverage / TestOnlyMetaFallsBack
// always agree.
package langspec

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

const compiledStatusFile = "COMPILED_STATUS.md"

func TestCompiledStatus(t *testing.T) {
	t.Parallel()
	c := gatherCensus(t)
	want := renderCompiledStatus(c)

	if os.Getenv("BORU_WRITE_STATUS") != "" {
		if err := os.WriteFile(compiledStatusFile, []byte(want), 0o644); err != nil {
			t.Fatalf("write %s: %v", compiledStatusFile, err)
		}
		t.Logf("wrote %s (%d bytes)", compiledStatusFile, len(want))
		return
	}

	got, err := os.ReadFile(compiledStatusFile)
	if err != nil {
		t.Fatalf("read %s: %v (run `make status` to generate it)", compiledStatusFile, err)
	}
	if string(got) != want {
		// Staleness is INFORMATIONAL, not a gate: a growing corpus moves these
		// counts constantly, and failing on every shift just forces regeneration
		// churn. Refresh with `make status` when you want the doc current.
		t.Logf("%s is stale (coverage moved) — refresh with `make status` if desired", compiledStatusFile)
	}
}

// renderCompiledStatus renders the census as the deterministic status document.
// Every histogram is sorted (most-frequent first, then name) so the output is
// byte-stable across runs and the golden compare is meaningful.
func renderCompiledStatus(c *census) string {
	var b strings.Builder

	b.WriteString("# Compiled-coverage status\n\n")
	b.WriteString("_Generated by `TestCompiledStatus` from the live `lang/spec/*.tsv` corpus — do not edit by hand._\n")
	b.WriteString("_Refresh with `make status` after any change that moves coverage. Staleness is INFORMATIONAL — a growing corpus moves these counts constantly, so `TestCompiledStatus` logs a stale file rather than failing on it (the CEILINGS are the gate, and they live in `TestCompiledCoverage`)._\n\n")

	compilable := c.rows - c.checkErr
	native := c.compiled - c.islanded
	b.WriteString(fmt.Sprintf("Corpus: **%d** spec value rows (**%d** compilable, %d statically invalid in both engines).\n\n",
		c.rows, compilable, c.checkErr))

	b.WriteString("## Disposition\n\n")
	b.WriteString("| outcome | rows |\n| --- | ---: |\n")
	b.WriteString(fmt.Sprintf("| compiled natively (fallback-free) | %d |\n", native))
	b.WriteString(fmt.Sprintf("| compiled with an interpreter island | %d |\n", c.islanded))
	b.WriteString(fmt.Sprintf("| refused (whole-program fallback) | %d |\n", c.refused))
	b.WriteString(fmt.Sprintf("| static check-error (invalid in both engines) | %d |\n", c.checkErr))
	if compilable > 0 {
		b.WriteString(fmt.Sprintf("\n**%d / %d** compilable rows produce a Program (%d%% — %d of those fully native).\n\n",
			c.compiled, compilable, c.compiled*100/compilable, native))
	}

	b.WriteString("## Ceilings (downward ratchets toward runtime independence)\n\n")
	b.WriteString("The compiler is interpreter-independent once refusals and islands both reach 0 and only tier 1 falls back. Each ceiling never rises.\n\n")
	b.WriteString("| ratchet | current | ceiling | finish line |\n| --- | ---: | ---: | --- |\n")
	b.WriteString(fmt.Sprintf("| refusals (whole-program fallback) | %d | %d | → 0 |\n", c.refused, refusalCeiling))
	b.WriteString(fmt.Sprintf("| interpreter islands (OpFallback) | %d | %d | → 0 |\n", c.islanded, islandCeiling))
	b.WriteString(fmt.Sprintf("| tier 1 interpreter-only | %d | %d | capped (permanent) |\n", c.interp, interpreterOnlyCeiling))
	b.WriteString(fmt.Sprintf("| tier 2 reducible | %d | %d | → 0 |\n", c.reducible, reducibleCeiling))
	b.WriteString(fmt.Sprintf("| compute frontier | %d | %d | → 0 |\n\n", c.computeGap, computeRefusalCeiling))

	b.WriteString("## Refusals by reason\n\n")
	if c.refused == 0 {
		b.WriteString("_No refusals._\n\n")
	} else {
		byCause := map[string]int{}
		b.WriteString("| count | bucket | root cause |\n| ---: | --- | --- |\n")
		for _, r := range sortedKeys(c.refusalBuckets) {
			b.WriteString(fmt.Sprintf("| %d | %s | %s |\n", c.refusalBuckets[r], r, rootCause(r)))
			byCause[rootCause(r)] += c.refusalBuckets[r]
		}
		b.WriteString("\n| root cause | refusals |\n| --- | ---: |\n")
		for _, cause := range []string{"correct-error", "soundness", "scheduling", "opcode", "coverage"} {
			b.WriteString(fmt.Sprintf("| %s | %d |\n", cause, byCause[cause]))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Re-scoped P7 partition\n\n")
	b.WriteString(fmt.Sprintf("Over the %d not-fully-native rows (refused or islanded): **%d** interpreter-only (tier 1, permanent), **%d** reducible (tier 2, TODO), **%d** allowlisted error rows, **%d** compute-frontier gaps.\n\n",
		c.refused+c.islanded, c.interp, c.reducible, c.errorRows, c.computeGap))

	writeHist(&b, "### tier 1 — interpreter-only (permanent home of the island)", "word", c.tier1By)
	writeHist(&b, "### tier 2 — reducible, not yet compiled", "word", c.tier2By)
	writeHist(&b, "### compute frontier by reason", "reason", c.computeBy)

	return b.String()
}

// writeHist appends a sorted (most-frequent first) "count | label" table, or a
// placeholder when the histogram is empty.
func writeHist(b *strings.Builder, heading, label string, m map[string]int) {
	b.WriteString(heading)
	b.WriteString("\n\n")
	if len(m) == 0 {
		b.WriteString("_None._\n\n")
		return
	}
	fmt.Fprintf(b, "| count | %s |\n| ---: | --- |\n", label)
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if m[keys[i]] != m[keys[j]] {
			return m[keys[i]] > m[keys[j]]
		}
		return keys[i] < keys[j]
	})
	for _, k := range keys {
		fmt.Fprintf(b, "| %d | %s |\n", m[k], k)
	}
	b.WriteString("\n")
}
